
-- ARTEMIS
-- PRD - Arquitectos
--  COFIDIS2000\GRP_SQL_ARQUITECTOS
--

use master
go
IF EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_ARQUITECTOS')
     DROP LOGIN [COFIDIS2000\GRP_SQL_ARQUITECTOS];
GO  

IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_ARQUITECTOS')
     CREATE LOGIN [COFIDIS2000\GRP_SQL_ARQUITECTOS] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english];
GO    


EXEC sp_MSforeachdb '
IF ''?'' NOT IN (''master'', ''model'', ''msdb'', ''SSISDB'', ''tempdb''
,''ACCIPIENS''
,''ContactCenter360''
,''Cofinet''
,''dba_db''
,''dba_local''
,''DevContactCenter360''
,''m-it2008''
,''Oauth''
,''ODMDC''
,''ODMDS''
,''ODMDSR''
,''ODMDSRDB''
,''osSessionLifetime''
,''OutSystems_Log''
,''OutSystemsLifeTime''
,''OutSystemsLifeTime_Log''
,''QualContactCenter360''
,''RH''
,''RptServer''
,''ScoreAuto''
,''Nomia''

) 
BEGIN 
    USE [?]
    PRINT ''?''
	DROP SCHEMA IF EXISTS [COFIDIS2000\GRP_SQL_ARQUITECTOS]
	DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_ARQUITECTOS]

    IF DATABASE_PRINCIPAL_ID(''COFIDIS2000\GRP_SQL_ARQUITECTOS'') IS NULL
    BEGIN
        PRINT '' Criando o user.''
        CREATE USER [COFIDIS2000\GRP_SQL_ARQUITECTOS] FROM LOGIN [COFIDIS2000\GRP_SQL_ARQUITECTOS];
    END /*IF*/
    PRINT '' Adicionar as permissões para o user ...''
	GRANT CONNECT TO [COFIDIS2000\GRP_SQL_ARQUITECTOS]
	GRANT SELECT TO [COFIDIS2000\GRP_SQL_ARQUITECTOS] 
	GRANT VIEW Definition 		TO [COFIDIS2000\GRP_SQL_ARQUITECTOS]

END /*IF*/
'


/*
--Privilégios MSDB
*/
USE [msdb]
GO
DROP SCHEMA IF EXISTS [COFIDIS2000\GRP_SQL_ARQUITECTOS]
DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_ARQUITECTOS]
go
IF NOT EXISTS (SELECT NAME FROM sys.database_principals WHERE NAME =  'COFIDIS2000\GRP_SQL_ARQUITECTOS') BEGIN CREATE USER  [COFIDIS2000\GRP_SQL_ARQUITECTOS] 
   FOR LOGIN [COFIDIS2000\GRP_SQL_ARQUITECTOS] END ELSE ALTER USER  [COFIDIS2000\GRP_SQL_ARQUITECTOS] WITH LOGIN = [COFIDIS2000\GRP_SQL_ARQUITECTOS];
IF DATABASE_PRINCIPAL_ID('COFIDIS2000\GRP_SQL_ARQUITECTOS') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\GRP_SQL_ARQUITECTOS]

exec sp_addrolemember 'SQLAgentReaderRole', 'COFIDIS2000\GRP_SQL_ARQUITECTOS'
exec sp_addrolemember 'db_ssisoperator', 'COFIDIS2000\GRP_SQL_ARQUITECTOS'
exec sp_addrolemember 'db_ssisltduser', 'COFIDIS2000\GRP_SQL_ARQUITECTOS'
exec sp_addrolemember 'db_datareader', 'COFIDIS2000\GRP_SQL_ARQUITECTOS'

/*
--Privilégios SSISDB
*/
USE [SSISDB]
GO
DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_ARQUITECTOS]
go
IF NOT EXISTS (SELECT NAME FROM sys.database_principals WHERE NAME =  'COFIDIS2000\GRP_SQL_ARQUITECTOS') BEGIN CREATE USER  [COFIDIS2000\GRP_SQL_ARQUITECTOS] 
   FOR LOGIN [COFIDIS2000\GRP_SQL_ARQUITECTOS] END ELSE ALTER USER  [COFIDIS2000\GRP_SQL_ARQUITECTOS] WITH LOGIN = [COFIDIS2000\GRP_SQL_ARQUITECTOS];
IF DATABASE_PRINCIPAL_ID('COFIDIS2000\GRP_SQL_ARQUITECTOS') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\GRP_SQL_ARQUITECTOS]

ALTER ROLE [db_datareader] ADD MEMBER [COFIDIS2000\GRP_SQL_ARQUITECTOS]
GO
ALTER ROLE [ssis_logreader] ADD MEMBER [COFIDIS2000\GRP_SQL_ARQUITECTOS]
GO
ALTER ROLE [ssis_admin] ADD MEMBER [COFIDIS2000\GRP_SQL_ARQUITECTOS]
GO

/* Excepções */
USE OutSystems
GO 
grant VIEW DATABASE STATE to [COFIDIS2000\GRP_SQL_ARQUITECTOS]
go




---
-- PRD - SENIORES
--  COFIDIS2000\GRP_SQL_SENIOR_PRD
--

use master
go
IF EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_SENIOR_PRD')
     DROP LOGIN [COFIDIS2000\GRP_SQL_SENIOR_PRD];
GO  

IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_SENIOR_PRD')
     CREATE LOGIN [COFIDIS2000\GRP_SQL_SENIOR_PRD] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english];
GO    



EXEC sp_MSforeachdb '
IF ''?'' NOT IN (''master'', ''model'', ''msdb'', ''SSISDB'', ''tempdb''
,''ACCIPIENS''
,''ContactCenter360''
,''Cofinet''
,''dba_db''
,''dba_local''
,''DevContactCenter360''
,''m-it2008''
,''Oauth''
,''ODMDC''
,''ODMDS''
,''ODMDSR''
,''ODMDSRDB''
,''osSessionLifetime''
,''OutSystems_Log''
,''OutSystemsLifeTime''
,''OutSystemsLifeTime_Log''
,''QualContactCenter360''
,''RH''
,''RptServer''
,''ScoreAuto''
,''SSISDB''
,''Nomia''

) 
BEGIN 
    USE [?]
    PRINT ''?''
	DROP SCHEMA IF EXISTS [COFIDIS2000\GRP_SQL_SENIOR_PRD]
	DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_SENIOR_PRD]

    IF DATABASE_PRINCIPAL_ID(''COFIDIS2000\GRP_SQL_SENIOR_PRD'') IS NULL
    BEGIN
        PRINT '' Criando o user.''
        CREATE USER [COFIDIS2000\GRP_SQL_SENIOR_PRD] FROM LOGIN [COFIDIS2000\GRP_SQL_SENIOR_PRD];
    END /*IF*/
    PRINT '' Adicionar as permissões para o user ...''
	GRANT CONNECT TO [COFIDIS2000\GRP_SQL_SENIOR_PRD]
	GRANT SELECT TO [COFIDIS2000\GRP_SQL_SENIOR_PRD]
	GRANT VIEW Definition 	TO [COFIDIS2000\GRP_SQL_SENIOR_PRD]	

END /*IF*/

'


/*
--Privilégios MSDB
*/
USE [msdb]
GO
DROP SCHEMA IF EXISTS [COFIDIS2000\GRP_SQL_SENIOR_PRD]
DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_SENIOR_PRD]
go
IF NOT EXISTS (SELECT NAME FROM sys.database_principals WHERE NAME =  'COFIDIS2000\GRP_SQL_SENIOR_PRD') BEGIN CREATE USER  [COFIDIS2000\GRP_SQL_SENIOR_PRD] 
   FOR LOGIN [COFIDIS2000\GRP_SQL_SENIOR_PRD] END ELSE ALTER USER  [COFIDIS2000\GRP_SQL_SENIOR_PRD] WITH LOGIN = [COFIDIS2000\GRP_SQL_SENIOR_PRD];
IF DATABASE_PRINCIPAL_ID('COFIDIS2000\GRP_SQL_SENIOR_PRD') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\GRP_SQL_SENIOR_PRD]

exec sp_addrolemember 'SQLAgentReaderRole', 'COFIDIS2000\GRP_SQL_SENIOR_PRD'
exec sp_addrolemember 'db_ssisoperator', 'COFIDIS2000\GRP_SQL_SENIOR_PRD'
exec sp_addrolemember 'db_ssisltduser', 'COFIDIS2000\GRP_SQL_SENIOR_PRD'
exec sp_addrolemember 'db_datareader', 'COFIDIS2000\GRP_SQL_SENIOR_PRD'

/*
--Privilégios SSISDB
*/
USE [SSISDB]
GO
DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_SENIOR_PRD]
go
IF NOT EXISTS (SELECT NAME FROM sys.database_principals WHERE NAME =  'COFIDIS2000\GRP_SQL_SENIOR_PRD') BEGIN CREATE USER  [COFIDIS2000\GRP_SQL_SENIOR_PRD] 
   FOR LOGIN [COFIDIS2000\GRP_SQL_SENIOR_PRD] END ELSE ALTER USER  [COFIDIS2000\GRP_SQL_SENIOR_PRD] WITH LOGIN = [COFIDIS2000\GRP_SQL_SENIOR_PRD];
IF DATABASE_PRINCIPAL_ID('COFIDIS2000\GRP_SQL_SENIOR_PRD') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\GRP_SQL_SENIOR_PRD]

ALTER ROLE [db_datareader] ADD MEMBER [COFIDIS2000\GRP_SQL_SENIOR_PRD]
GO
ALTER ROLE [ssis_logreader] ADD MEMBER [COFIDIS2000\GRP_SQL_SENIOR_PRD]
GO
ALTER ROLE [ssis_admin] ADD MEMBER [COFIDIS2000\GRP_SQL_SENIOR_PRD]
GO


--
-- SUPORTE - Suporte aplicacional
--  COFIDIS2000\GRP_SQL_SUPORTE_APP
--

use master
go
IF EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_SUPORTE_APP')
     DROP LOGIN [COFIDIS2000\GRP_SQL_SUPORTE_APP];
GO  

IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_SUPORTE_APP')
     CREATE LOGIN [COFIDIS2000\GRP_SQL_SUPORTE_APP] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english];
GO    


EXEC sp_MSforeachdb '
IF ''?'' NOT IN (''master'', ''model'', ''msdb'', ''SSISDB'', ''tempdb''
,''copia_dev''
,''ContactCenter360''
,''dba_db''
,''dba_local''
,''DevContactCenter360''
,''OutSystems_Log''
,''OutSystemsLifeTime_Log''
,''PaymentGateway''
,''RH''
,''RptServer''


) 
BEGIN 
    USE [?]
    PRINT ''?''
	DROP SCHEMA IF EXISTS [COFIDIS2000\GRP_SQL_SUPORTE_APP]
	DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_SUPORTE_APP]

    IF DATABASE_PRINCIPAL_ID(''COFIDIS2000\GRP_SQL_SUPORTE_APP'') IS NULL
    BEGIN
        PRINT '' Criando o user.''
        CREATE USER [COFIDIS2000\GRP_SQL_SUPORTE_APP] FROM LOGIN [COFIDIS2000\GRP_SQL_SUPORTE_APP];
    END /*IF*/
    PRINT '' Adicionar as permissões para o user ...''
	GRANT CONNECT TO [COFIDIS2000\GRP_SQL_SUPORTE_APP]
	GRANT SELECT, UPDATE,INSERT  TO [COFIDIS2000\GRP_SQL_SUPORTE_APP] 
	GRANT VIEW Definition 		TO [COFIDIS2000\GRP_SQL_SUPORTE_APP]
	GRANT EXECUTE 				TO [COFIDIS2000\GRP_SQL_SUPORTE_APP]

END /*IF*/
'


/*
--Privilégios MSDB
*/
USE [msdb]
GO
DROP SCHEMA IF EXISTS [COFIDIS2000\GRP_SQL_SUPORTE_APP]
DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_SUPORTE_APP]
go
IF NOT EXISTS (SELECT NAME FROM sys.database_principals WHERE NAME =  'COFIDIS2000\GRP_SQL_SUPORTE_APP') BEGIN CREATE USER  [COFIDIS2000\GRP_SQL_SUPORTE_APP] 
   FOR LOGIN [COFIDIS2000\GRP_SQL_SUPORTE_APP] END ELSE ALTER USER  [COFIDIS2000\GRP_SQL_SUPORTE_APP] WITH LOGIN = [COFIDIS2000\GRP_SQL_SUPORTE_APP];
IF DATABASE_PRINCIPAL_ID('COFIDIS2000\GRP_SQL_SUPORTE_APP') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\GRP_SQL_SUPORTE_APP]

exec sp_addrolemember 'SQLAgentOperatorRole', 'COFIDIS2000\GRP_SQL_SUPORTE_APP'
exec sp_addrolemember 'db_ssisoperator', 'COFIDIS2000\GRP_SQL_SUPORTE_APP'
exec sp_addrolemember 'db_ssisltduser', 'COFIDIS2000\GRP_SQL_SUPORTE_APP'
exec sp_addrolemember 'db_datareader', 'COFIDIS2000\GRP_SQL_SUPORTE_APP'

/*
--Privilégios SSISDB
*/
USE [SSISDB]
GO
DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_SUPORTE_APP]
go
IF NOT EXISTS (SELECT NAME FROM sys.database_principals WHERE NAME =  'COFIDIS2000\GRP_SQL_SUPORTE_APP') BEGIN CREATE USER  [COFIDIS2000\GRP_SQL_SUPORTE_APP] 
   FOR LOGIN [COFIDIS2000\GRP_SQL_SUPORTE_APP] END ELSE ALTER USER  [COFIDIS2000\GRP_SQL_SUPORTE_APP] WITH LOGIN = [COFIDIS2000\GRP_SQL_SUPORTE_APP];
IF DATABASE_PRINCIPAL_ID('COFIDIS2000\GRP_SQL_SUPORTE_APP') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\GRP_SQL_SUPORTE_APP]

ALTER ROLE [db_datareader] ADD MEMBER [COFIDIS2000\GRP_SQL_SUPORTE_APP]
GO
ALTER ROLE [ssis_logreader] ADD MEMBER [COFIDIS2000\GRP_SQL_SUPORTE_APP]
GO
USE master
go 
GRANT ADMINISTER BULK OPERATIONS to [COFIDIS2000\GRP_SQL_SUPORTE_APP]

----
-- Privilegios adicionais
USE AdministracaoSistemas
GRANT DELETE TO [COFIDIS2000\GRP_SQL_SUPORTE_APP];

USE fastapp
go
GRANT ALTER TO [COFIDIS2000\GRP_SQL_SUPORTE_APP]





-- Factories -- SENIORES

--
-- Factori4es

--
-- PRD - Factori4es
--  COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR
--

use master
go
IF EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR')
     DROP LOGIN [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR];
GO  

IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR')
     CREATE LOGIN [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english];
GO    


EXEC sp_MSforeachdb '
IF ''?'' NOT IN (''master'', ''model'', ''msdb'', ''SSISDB'', ''tempdb''
,''ACCIPIENS''
,''AdministracaoSistemas''
,''CC''
,''CobrancasDAH''
,''Cofinet''
,''Comunicacoes''
,''ContactCenter360''
,''copia_dev''
,''db_cofidis_dah''
,''dba_db''
,''dba_local''
,''DevContactCenter360''
,''DocsMgrServer''
,''DotNetNuke''
,''ExtraccaoTREC''
,''fastapp''
,''FileWatcher''
,''FM''
,''GestaoEconomato''
,''HBK''
,''Insurance''
,''LogginApp''
,''Marketing''
,''master''
,''m-it2008''
,''model''
,''msdb''
,''Oauth''
,''ODMDC''
,''ODMDS''
,''ODMDSR''
,''ODMDSRDB''
,''OSASPState''
,''osSessionLifetime''
,''OutSystems_Log''
,''OutSystems_Log2023''
,''OutSystemsLifeTime''
,''OutSystemsLifeTime_Log''
,''pac-pac''
,''PaymentGateway''
,''QualContactCenter360''
,''RH''
,''RptServer''
,''RUP''
,''ScoreAuto''
,''SSISDB''
,''TControl''
,''TcontrolDAH''
,''TcontrolDAH_Ops''
,''tempdb''


) 
BEGIN 
    USE [?]
    PRINT ''?''
	DROP SCHEMA IF EXISTS [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR]
	DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR]

    IF DATABASE_PRINCIPAL_ID(''COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR'') IS NULL
    BEGIN
        PRINT '' Criando o user.''
        CREATE USER [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR] FROM LOGIN [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR];
    END /*IF*/
    PRINT '' Adicionar as permissões para o user ...''
	GRANT CONNECT TO [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR]
	GRANT SELECT				 TO [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR] 

END /*IF*/
'


/*
--Privilégios MSDB
*/
USE [msdb]
GO
DROP SCHEMA IF EXISTS [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR]
DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR]
go
IF NOT EXISTS (SELECT NAME FROM sys.database_principals WHERE NAME =  'COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR') BEGIN CREATE USER  [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR] 
   FOR LOGIN [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR] END ELSE ALTER USER  [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR] WITH LOGIN = [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR];
IF DATABASE_PRINCIPAL_ID('COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR]

exec sp_addrolemember 'db_ssisltduser', 'COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR'
exec sp_addrolemember 'db_datareader', 'COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR'

/*
--Privilégios SSISDB
*/
USE [SSISDB]
GO
DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR]
go
IF NOT EXISTS (SELECT NAME FROM sys.database_principals WHERE NAME =  'COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR') BEGIN CREATE USER  [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR] 
   FOR LOGIN [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR] END ELSE ALTER USER  [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR] WITH LOGIN = [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR];
IF DATABASE_PRINCIPAL_ID('COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR]

ALTER ROLE [db_datareader] ADD MEMBER [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR]
GO
ALTER ROLE [ssis_logreader] ADD MEMBER [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR]
GO

-- KPIs

--
-- PRD -
--  COFIDIS2000\GRP_SQL_KPIS
--

use master
go
IF EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_KPIS')
     DROP LOGIN [COFIDIS2000\GRP_SQL_KPIS];
GO  

IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_KPIS')
     CREATE LOGIN [COFIDIS2000\GRP_SQL_KPIS] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english];
GO    


EXEC sp_MSforeachdb '
IF ''?'' NOT IN (''master'', ''model'', ''msdb'', ''SSISDB'', ''tempdb''
,''ACCIPIENS''
,''AdministracaoSistemas''
,''AppFabric''
,''ASPState''
,''CC''
,''CobrancasDAH''
,''Cofinet''
,''Comunicacoes''
,''ContactCenter360''
,''copia_dev''
,''db_cofidis_dah''
,''dba_db''
,''dba_local''
,''DSTI''
,''DevContactCenter360''
,''DocsMgrServer''
,''DotNetNuke''
,''ExtraccaoTREC''
,''fastapp''
,''FileWatcher''
,''FM''
,''GestaoEconomato''
,''HBK''
,''Insurance''
,''IDH''
,''LogginApp''
,''Marketing''
,''master''
,''m-it2008''
,''model''
,''msdb''
,''Oauth''
,''ODMDC''
,''ODMDS''
,''ODMDSR''
,''ODMDSRDB''
,''OSASPState''
,''osSessionLifetime''
,''OutSystems''
,''OutSystems_Log''
,''OutSystems_Log2023''
,''OutSystemsLifeTime''
,''OutSystemsLifeTime_Log''
,''pac-pac''
,''PaymentGateway''
,''QualContactCenter360''
,''RH''
,''RptServer''
,''RUP''
,''ScoreAuto''
,''ServiceGate''
,''SSISDB''
,''TControl''
,''TcontrolDAH''
,''TcontrolDAH_Ops''
,''tempdb''
,''Threatmetrix''

) 
BEGIN 
    USE [?]
    PRINT ''?''
	DROP SCHEMA IF EXISTS [COFIDIS2000\GRP_SQL_KPIS]
	DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_KPIS]

    IF DATABASE_PRINCIPAL_ID(''COFIDIS2000\GRP_SQL_KPIS'') IS NULL
    BEGIN
        PRINT '' Criando o user.''
        CREATE USER [COFIDIS2000\GRP_SQL_KPIS] FROM LOGIN [COFIDIS2000\GRP_SQL_KPIS];
    END /*IF*/
    PRINT '' Adicionar as permissões para o user ...''
	GRANT CONNECT TO [COFIDIS2000\GRP_SQL_KPIS]
	GRANT SELECT				 TO [COFIDIS2000\GRP_SQL_KPIS] 


END /*IF*/
'


/*
--Privilégios MSDB
*/
USE [msdb]
GO
DROP SCHEMA IF EXISTS [COFIDIS2000\GRP_SQL_KPIS]
DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_KPIS]
go
IF NOT EXISTS (SELECT NAME FROM sys.database_principals WHERE NAME =  'COFIDIS2000\GRP_SQL_KPIS') BEGIN CREATE USER  [COFIDIS2000\GRP_SQL_KPIS] 
   FOR LOGIN [COFIDIS2000\GRP_SQL_KPIS] END ELSE ALTER USER  [COFIDIS2000\GRP_SQL_KPIS] WITH LOGIN = [COFIDIS2000\GRP_SQL_KPIS];
IF DATABASE_PRINCIPAL_ID('COFIDIS2000\GRP_SQL_KPIS') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\GRP_SQL_KPIS]

exec sp_addrolemember 'db_ssisltduser', 'COFIDIS2000\GRP_SQL_KPIS'
exec sp_addrolemember 'db_datareader', 'COFIDIS2000\GRP_SQL_KPIS'

-- BILLING

--
-- PRD - 
--  COFIDIS2000\GRP_SQL_BILLING_SENIOR
--

use master
go
IF EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_BILLING_SENIOR')
     DROP LOGIN [COFIDIS2000\GRP_SQL_BILLING_SENIOR];
GO  

IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_BILLING_SENIOR')
     CREATE LOGIN [COFIDIS2000\GRP_SQL_BILLING_SENIOR] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english];
GO    


EXEC sp_MSforeachdb '
IF ''?'' NOT IN (''master'', ''model'', ''msdb'', ''SSISDB'', ''tempdb''
,''ACCIPIENS''
,''AdministracaoSistemas''
,''AppFabric''
,''ASPState''

,''CC''
,''Cofinet''
,''ContactCenter360''
,''copia_dev''
,''db_cofidis_dah''
,''DB_KPI''
,''dba_db''
,''dba_local''
,''DSTI''
,''DevContactCenter360''
,''DocsMgrServer''
,''DotNetNuke''
,''ExtraccaoTREC''
,''fastapp''
,''GestaoEconomato''
,''HBK''
,''Insurance''
,''IDH''
,''LogginApp''
,''Marketing''
,''master''
,''m-it2008''
,''model''
,''msdb''
,''Oauth''
,''ODMDC''
,''ODMDS''
,''ODMDSR''
,''ODMDSRDB''
,''OSASPState''
,''osSessionLifetime''
,''OutSystems''
,''OutSystems_Log''
,''OutSystems_Log2023''
,''OutSystemsLifeTime''
,''OutSystemsLifeTime_Log''
,''pac-pac''
,''PaymentGateway''
,''QualContactCenter360''
,''RH''
,''RptServer''
,''RUP''
,''ScoreAuto''
,''ServiceGate''
,''SSISDB''
,''tempdb''
,''Threatmetrix''

) 
BEGIN 
    USE [?]
    PRINT ''?''
	DROP SCHEMA IF EXISTS [COFIDIS2000\GRP_SQL_BILLING_SENIOR]
	DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_BILLING_SENIOR]

    IF DATABASE_PRINCIPAL_ID(''COFIDIS2000\GRP_SQL_BILLING_SENIOR'') IS NULL
    BEGIN
        PRINT '' Criando o user.''
        CREATE USER [COFIDIS2000\GRP_SQL_BILLING_SENIOR] FROM LOGIN [COFIDIS2000\GRP_SQL_BILLING_SENIOR];
    END /*IF*/
    PRINT '' Adicionar as permissões para o user ...''
	GRANT CONNECT 				 TO [COFIDIS2000\GRP_SQL_BILLING_SENIOR]
	GRANT SELECT   TO [COFIDIS2000\GRP_SQL_BILLING_SENIOR] 
	GRANT EXECUTE 				 TO [COFIDIS2000\GRP_SQL_BILLING_SENIOR]
	GRANT VIEW Definition 	     TO [COFIDIS2000\GRP_SQL_BILLING_SENIOR]

END /*IF*/
'


/*
--Privilégios MSDB
*/
USE [msdb]
GO
DROP SCHEMA IF EXISTS [COFIDIS2000\GRP_SQL_BILLING_SENIOR]
DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_BILLING_SENIOR]
go
IF NOT EXISTS (SELECT NAME FROM sys.database_principals WHERE NAME =  'COFIDIS2000\GRP_SQL_BILLING_SENIOR') BEGIN CREATE USER  [COFIDIS2000\GRP_SQL_BILLING_SENIOR] 
   FOR LOGIN [COFIDIS2000\GRP_SQL_BILLING_SENIOR] END ELSE ALTER USER  [COFIDIS2000\GRP_SQL_BILLING_SENIOR] WITH LOGIN = [COFIDIS2000\GRP_SQL_BILLING_SENIOR];
IF DATABASE_PRINCIPAL_ID('COFIDIS2000\GRP_SQL_BILLING_SENIOR') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\GRP_SQL_BILLING_SENIOR]

exec sp_addrolemember 'SQLAgentOperatorRole', 'COFIDIS2000\GRP_SQL_BILLING_SENIOR'
exec sp_addrolemember 'db_ssisoperator', 'COFIDIS2000\GRP_SQL_BILLING_SENIOR'
exec sp_addrolemember 'db_ssisltduser', 'COFIDIS2000\GRP_SQL_BILLING_SENIOR'
exec sp_addrolemember 'db_datareader', 'COFIDIS2000\GRP_SQL_BILLING_SENIOR'

USE [SSISDB]
GO
DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_BILLING_SENIOR]
go
IF NOT EXISTS (SELECT NAME FROM sys.database_principals WHERE NAME =  'COFIDIS2000\GRP_SQL_BILLING_SENIOR') BEGIN CREATE USER  [COFIDIS2000\GRP_SQL_BILLING_SENIOR] 
   FOR LOGIN [COFIDIS2000\GRP_SQL_BILLING_SENIOR] END ELSE ALTER USER  [COFIDIS2000\GRP_SQL_BILLING_SENIOR] WITH LOGIN = [COFIDIS2000\GRP_SQL_BILLING_SENIOR];
IF DATABASE_PRINCIPAL_ID('COFIDIS2000\GRP_SQL_BILLING_SENIOR') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\GRP_SQL_BILLING_SENIOR]

ALTER ROLE [db_datareader] ADD MEMBER [COFIDIS2000\GRP_SQL_BILLING_SENIOR]
GO
ALTER ROLE [ssis_logreader] ADD MEMBER [COFIDIS2000\GRP_SQL_BILLING_SENIOR]
GO

USE [CobrancasDAH]
GO
CREATE USER [COFIDIS2000\GRP_SQL_BILLING_SENIOR] FOR LOGIN [COFIDIS2000\GRP_SQL_BILLING_SENIOR]
GO
ALTER ROLE [db_datareader] ADD MEMBER [COFIDIS2000\GRP_SQL_BILLING_SENIOR]
GO
USE [FileWatcher]
GO
CREATE USER [COFIDIS2000\GRP_SQL_BILLING_SENIOR] FOR LOGIN [COFIDIS2000\GRP_SQL_BILLING_SENIOR]
GO
ALTER ROLE [db_datareader] ADD MEMBER [COFIDIS2000\GRP_SQL_BILLING_SENIOR]
GO
USE [FM]
GO
CREATE USER [COFIDIS2000\GRP_SQL_BILLING_SENIOR] FOR LOGIN [COFIDIS2000\GRP_SQL_BILLING_SENIOR]
GO
ALTER ROLE [db_datareader] ADD MEMBER [COFIDIS2000\GRP_SQL_BILLING_SENIOR]
GO
USE [Comunicacoes]
GO
CREATE USER [COFIDIS2000\GRP_SQL_BILLING_SENIOR] FOR LOGIN [COFIDIS2000\GRP_SQL_BILLING_SENIOR]
GO
ALTER ROLE [db_datareader] ADD MEMBER [COFIDIS2000\GRP_SQL_BILLING_SENIOR]
GO




-- PRD - ARQUITECTURA & ENGENHARIA
--  COFIDIS2000\GRP_SQL_AENG
--  HESTIA

use master
go
IF EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_AENG')
     DROP LOGIN [COFIDIS2000\GRP_SQL_AENG];
GO  

IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_AENG')
     CREATE LOGIN [COFIDIS2000\GRP_SQL_AENG] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english];
GO    


EXEC sp_MSforeachdb '
IF ''?'' NOT IN (''master'', ''model'', ''msdb'', ''SSISDB'', ''tempdb''

,''ACCIPIENS''
,''AdministracaoSistemas''
,''AppFabric''
,''ASPState''
,''CC''
,''CobrancasDAH''
,''Cofinet''
,''Comunicacoes''
,''ContactCenter360''
,''copia_dev''
,''db_cofidis_dah''
,''DB_KPI''
,''dba_db''
,''dba_local''
,''DevContactCenter360''
,''DocsMgrServer''
,''DotNetNuke''
,''DSTI''
,''ExtraccaoTREC''
,''fastapp''
,''FileWatcher''
,''FM''
,''GestaoEconomato''
,''HBK''
,''IDH''
,''Insurance''
,''LogginApp''
,''Marketing''
,''m-it2008''
,''Oauth''
,''ODMDC''
,''ODMDS''
,''ODMDSR''
,''ODMDSRDB''
,''OSASPState''
,''osSessionLifetime''
,''OutSystemsLifeTime''
,''OutSystemsLifeTime_Log''
,''pac-pac''
,''PaymentGateway''
,''QualContactCenter360''
,''RH''
,''RptServer''
,''RUP''
,''ScoreAuto''
,''ServiceGate''
,''SSISDB''
,''TControl''
,''TcontrolDAH''
,''TcontrolDAH_Ops''
,''Threatmetrix''

) 
BEGIN 
    USE [?]
    PRINT ''?''
	DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_AENG]

    IF DATABASE_PRINCIPAL_ID(''COFIDIS2000\GRP_SQL_AENG'') IS NULL
    BEGIN
        PRINT '' Criando o user.''
        CREATE USER [COFIDIS2000\GRP_SQL_AENG] FROM LOGIN [COFIDIS2000\GRP_SQL_AENG];
    END /*IF*/
    PRINT '' Adicionar as permissões para o user ...''
	GRANT CONNECT TO [COFIDIS2000\GRP_SQL_AENG]
	GRANT SELECT TO [COFIDIS2000\GRP_SQL_AENG]  
	GRANT SHOWPLAN 				TO [COFIDIS2000\GRP_SQL_AENG]

END /*IF*/
'


/*
--Privilégios MSDB
*/
USE [msdb]
GO
DROP SCHEMA IF EXISTS [COFIDIS2000\GRP_SQL_AENG]
DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_AENG]
go
IF NOT EXISTS (SELECT NAME FROM sys.database_principals WHERE NAME =  'COFIDIS2000\GRP_SQL_AENG') BEGIN CREATE USER  [COFIDIS2000\GRP_SQL_AENG] 
   FOR LOGIN [COFIDIS2000\GRP_SQL_AENG] END ELSE ALTER USER  [COFIDIS2000\GRP_SQL_AENG] WITH LOGIN = [COFIDIS2000\GRP_SQL_AENG];
IF DATABASE_PRINCIPAL_ID('COFIDIS2000\GRP_SQL_AENG') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\GRP_SQL_AENG]

exec sp_addrolemember 'SQLAgentUserRole', 'COFIDIS2000\GRP_SQL_AENG'
exec sp_addrolemember 'db_ssisoperator', 'COFIDIS2000\GRP_SQL_AENG'
exec sp_addrolemember 'db_datareader', 'COFIDIS2000\GRP_SQL_AENG'

/*
--Privilégios SSISDB
*/
USE [SSISDB]
GO
DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_AENG]
go
IF NOT EXISTS (SELECT NAME FROM sys.database_principals WHERE NAME =  'COFIDIS2000\GRP_SQL_AENG') BEGIN CREATE USER  [COFIDIS2000\GRP_SQL_AENG] 
   FOR LOGIN [COFIDIS2000\GRP_SQL_AENG] END ELSE ALTER USER  [COFIDIS2000\GRP_SQL_AENG] WITH LOGIN = [COFIDIS2000\GRP_SQL_AENG];
IF DATABASE_PRINCIPAL_ID('COFIDIS2000\GRP_SQL_AENG') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\GRP_SQL_AENG]

ALTER ROLE [db_datareader] ADD MEMBER [COFIDIS2000\GRP_SQL_AENG]
GO


-----

-- BILLING JUNIOR

--
-- PRD - 
--  COFIDIS2000\GRP_SQL_BILLING_JUNIOR
--

use master
go
IF EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_BILLING_JUNIOR')
     DROP LOGIN [COFIDIS2000\GRP_SQL_BILLING_JUNIOR];
GO  

IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_BILLING_JUNIOR')
     CREATE LOGIN [COFIDIS2000\GRP_SQL_BILLING_JUNIOR] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english];
GO    


EXEC sp_MSforeachdb '
IF ''?'' NOT IN (''master'', ''model'', ''msdb'', ''SSISDB'', ''tempdb''
,''ACCIPIENS''
,''AdministracaoSistemas''
,''AppFabric''
,''ASPState''
,''CC''
,''Cofinet''
,''ContactCenter360''
,''copia_dev''
,''db_cofidis_dah''
,''DB_KPI''
,''dba_db''
,''dba_local''
,''DevContactCenter360''
,''DocsMgrServer''
,''DotNetNuke''
,''DSTI''
,''ExtraccaoTREC''
,''fastapp''
,''GestaoEconomato''
,''HBK''
,''Insurance''
,''LogginApp''
,''Marketing''
,''m-it2008''
,''Oauth''
,''ODMDC''
,''ODMDS''
,''ODMDSR''
,''ODMDSRDB''
,''OSASPState''
,''osSessionLifetime''
,''OutSystemsLifeTime''
,''OutSystemsLifeTime_Log''
,''pac-pac''
,''PaymentGateway''
,''QualContactCenter360''
,''RH''
,''RptServer''
,''RUP''
,''ScoreAuto''
,''ServiceGate''
,''SSISDB''
,''TControl''
,''TcontrolDAH_Ops''
,''Threatmetrix''


) 
BEGIN 
    USE [?]
    PRINT ''?''
	DROP SCHEMA IF EXISTS [COFIDIS2000\GRP_SQL_BILLING_JUNIOR]
	DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_BILLING_JUNIOR]

    IF DATABASE_PRINCIPAL_ID(''COFIDIS2000\GRP_SQL_BILLING_JUNIOR'') IS NULL
    BEGIN
        PRINT '' Criando o user.''
        CREATE USER [COFIDIS2000\GRP_SQL_BILLING_JUNIOR] FROM LOGIN [COFIDIS2000\GRP_SQL_BILLING_JUNIOR];
    END /*IF*/
    PRINT '' Adicionar as permissões para o user ...''
	GRANT CONNECT 				 TO [COFIDIS2000\GRP_SQL_BILLING_JUNIOR]
	GRANT SELECT				 TO [COFIDIS2000\GRP_SQL_BILLING_JUNIOR] 
	GRANT VIEW Definition		 TO [COFIDIS2000\GRP_SQL_BILLING_JUNIOR]


END /*IF*/
'


/*
--Privilégios MSDB
*/
USE [msdb]
GO
DROP SCHEMA IF EXISTS [COFIDIS2000\GRP_SQL_BILLING_JUNIOR]
DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_BILLING_JUNIOR]
go
IF NOT EXISTS (SELECT NAME FROM sys.database_principals WHERE NAME =  'COFIDIS2000\GRP_SQL_BILLING_JUNIOR') BEGIN CREATE USER  [COFIDIS2000\GRP_SQL_BILLING_JUNIOR] 
   FOR LOGIN [COFIDIS2000\GRP_SQL_BILLING_JUNIOR] END ELSE ALTER USER  [COFIDIS2000\GRP_SQL_BILLING_JUNIOR] WITH LOGIN = [COFIDIS2000\GRP_SQL_BILLING_JUNIOR];
IF DATABASE_PRINCIPAL_ID('COFIDIS2000\GRP_SQL_BILLING_JUNIOR') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\GRP_SQL_BILLING_JUNIOR]

exec sp_addrolemember 'SQLAgentOperatorRole', 'COFIDIS2000\GRP_SQL_BILLING_JUNIOR'
exec sp_addrolemember 'db_ssisoperator', 'COFIDIS2000\GRP_SQL_BILLING_JUNIOR'
exec sp_addrolemember 'db_ssisltduser', 'COFIDIS2000\GRP_SQL_BILLING_JUNIOR'
exec sp_addrolemember 'db_datareader', 'COFIDIS2000\GRP_SQL_BILLING_JUNIOR'

USE [SSISDB]
GO
DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_BILLING_JUNIOR]
go
IF NOT EXISTS (SELECT NAME FROM sys.database_principals WHERE NAME =  'COFIDIS2000\GRP_SQL_BILLING_JUNIOR') BEGIN CREATE USER  [COFIDIS2000\GRP_SQL_BILLING_JUNIOR] 
   FOR LOGIN [COFIDIS2000\GRP_SQL_BILLING_JUNIOR] END ELSE ALTER USER  [COFIDIS2000\GRP_SQL_BILLING_JUNIOR] WITH LOGIN = [COFIDIS2000\GRP_SQL_BILLING_JUNIOR];
IF DATABASE_PRINCIPAL_ID('COFIDIS2000\GRP_SQL_BILLING_JUNIOR') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\GRP_SQL_BILLING_JUNIOR]

ALTER ROLE [db_datareader] ADD MEMBER [COFIDIS2000\GRP_SQL_BILLING_JUNIOR]
GO
ALTER ROLE [ssis_admin] ADD MEMBER [COFIDIS2000\GRP_SQL_BILLING_JUNIOR]
GO

/* IDH
use master
go
IF EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_BILLING_JUNIOR')
     DROP LOGIN [COFIDIS2000\GRP_SQL_BILLING_JUNIOR];
GO  

IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_BILLING_JUNIOR')
     CREATE LOGIN [COFIDIS2000\GRP_SQL_BILLING_JUNIOR] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english];
GO    
use TCONTROLDAH

GRANT CONNECT 				 TO [COFIDIS2000\GRP_SQL_BILLING_JUNIOR]
GRANT SELECT				 TO [COFIDIS2000\GRP_SQL_BILLING_JUNIOR] 
go

*/


-- Novo Grupo "Cofinet" GRP_SQL_COFINET

--
-- PRD - 
--  COFIDIS2000\GRP_SQL_COFINET
--

use master
go
IF EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_COFINET')
     DROP LOGIN [COFIDIS2000\GRP_SQL_COFINET];
GO  

IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_COFINET')
     CREATE LOGIN [COFIDIS2000\GRP_SQL_COFINET] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english];
GO    


EXEC sp_MSforeachdb '
IF ''?''  IN (''Cofinet'') 
BEGIN 
    USE [?]
    PRINT ''?''
	DROP SCHEMA IF EXISTS [COFIDIS2000\GRP_SQL_COFINET]
	DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_COFINET]

    IF DATABASE_PRINCIPAL_ID(''COFIDIS2000\GRP_SQL_COFINET'') IS NULL
    BEGIN
        PRINT '' Criando o user.''
        CREATE USER [COFIDIS2000\GRP_SQL_COFINET] FROM LOGIN [COFIDIS2000\GRP_SQL_COFINET];
    END /*IF*/
    PRINT '' Adicionar as permissões para o user ...''
	GRANT CONNECT 				 TO [COFIDIS2000\GRP_SQL_COFINET]
	GRANT SELECT				 TO [COFIDIS2000\GRP_SQL_COFINET] 
	GRANT VIEW Definition	 TO [COFIDIS2000\GRP_SQL_COFINET]


END /*IF*/
'