-- PRD
--  Arquitectos
--

use master
go
IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_ARQUITECTOS')
     CREATE LOGIN [COFIDIS2000\GRP_SQL_ARQUITECTOS] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english];
GO    


EXEC sp_MSforeachdb '
IF ''?'' IN (''Paybylink''
) 
BEGIN 
    USE [?]
    PRINT ''?''
	DROP SCHEMA IF EXISTS [COFIDIS2000\GRP_SQL_ARQUITECTOS];
	DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_ARQUITECTOS]

    IF DATABASE_PRINCIPAL_ID(''COFIDIS2000\GRP_SQL_ARQUITECTOS'') IS NULL
    BEGIN
        PRINT '' Criando o user.''
        CREATE USER [COFIDIS2000\GRP_SQL_ARQUITECTOS] FROM LOGIN [COFIDIS2000\GRP_SQL_ARQUITECTOS];
    END /*IF*/
    PRINT '' Adicionar as permissões para o user ...''
	GRANT CONNECT TO [COFIDIS2000\GRP_SQL_ARQUITECTOS]
	GRANT SELECT TO [COFIDIS2000\GRP_SQL_ARQUITECTOS] 
	GRANT VIEW Definition 		TO [COFIDIS2000\GRP_SQL_ARQUITECTOS]


END /*IF*/
'



--
-- PRD
--  COFIDIS2000\GRP_SQL_DEV_SENIOR
--

use master
go

IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_DEV_SENIOR')
     CREATE LOGIN [COFIDIS2000\GRP_SQL_DEV_SENIOR] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english];
GO    



EXEC sp_MSforeachdb '
IF ''?'' IN (''Paybylink''
) 

BEGIN 
    USE [?]
    PRINT ''?''
	DROP SCHEMA IF EXISTS [COFIDIS2000\GRP_SQL_DEV_SENIOR];
	DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_DEV_SENIOR]

    IF DATABASE_PRINCIPAL_ID(''COFIDIS2000\GRP_SQL_DEV_SENIOR'') IS NULL
    BEGIN
        PRINT '' Criando o user.''
        CREATE USER [COFIDIS2000\GRP_SQL_DEV_SENIOR] FROM LOGIN [COFIDIS2000\GRP_SQL_DEV_SENIOR];
    END /*IF*/
    PRINT '' Adicionar as permissões para o user ...''
	GRANT CONNECT TO [COFIDIS2000\GRP_SQL_DEV_SENIOR]
	GRANT SELECT TO [COFIDIS2000\GRP_SQL_DEV_SENIOR] 
	GRANT VIEW Definition 		TO [COFIDIS2000\GRP_SQL_DEV_SENIOR]


END /*IF*/
'
--
--
-- PRD - 
--  COFIDIS2000\GRP_SQL_BILLING_SENIOR
--

use master
go

IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_BILLING_JUNIOR')
     CREATE LOGIN [COFIDIS2000\GRP_SQL_BILLING_JUNIOR] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english];
GO    


EXEC sp_MSforeachdb '
IF ''?'' IN (''Paybylink''

) 
BEGIN 
    USE [?]
    PRINT ''?''
	DROP SCHEMA IF EXISTS [COFIDIS2000\GRP_SQL_BILLING_JUNIOR]
	DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_BILLING_JUNIOR]

    IF DATABASE_PRINCIPAL_ID(''COFIDIS2000\GRP_SQL_BILLING_JUNIOR'') IS NULL
    BEGIN
        PRINT '' Criando o user.''
        CREATE USER [COFIDIS2000\GRP_SQL_BILLING_JUNIOR] FROM LOGIN [COFIDIS2000\GRP_SQL_BILLING_JUNIOR];
    END /*IF*/
    PRINT '' Adicionar as permissões para o user ...''
	GRANT CONNECT 				 TO [COFIDIS2000\GRP_SQL_BILLING_JUNIOR]
	GRANT SELECT		 TO [COFIDIS2000\GRP_SQL_BILLING_JUNIOR] 
	GRANT VIEW Definition 		TO [COFIDIS2000\GRP_SQL_BILLING_JUNIOR]

END /*IF*/
'



-- ARTEMIS - GRP_SQL_BILLING_SENIOR
--  COFIDIS2000\GRP_SQL_BILLING_SENIOR
--

use master
go
IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_BILLING_SENIOR')
     CREATE LOGIN [COFIDIS2000\GRP_SQL_BILLING_SENIOR] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english];
GO    


EXEC sp_MSforeachdb '
IF ''?'' IN (''Paybylink''

) 
BEGIN 
    USE [?]
    PRINT ''?''
	DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_BILLING_SENIOR]

    IF DATABASE_PRINCIPAL_ID(''COFIDIS2000\GRP_SQL_BILLING_SENIOR'') IS NULL
    BEGIN
        PRINT '' Criando o user.''
        CREATE USER [COFIDIS2000\GRP_SQL_BILLING_SENIOR] FROM LOGIN [COFIDIS2000\GRP_SQL_BILLING_SENIOR];
    END /*IF*/
    PRINT '' Adicionar as permissões para o user ...''
	GRANT CONNECT TO [COFIDIS2000\GRP_SQL_BILLING_SENIOR]
	GRANT SELECT TO [COFIDIS2000\GRP_SQL_BILLING_SENIOR] 

	GRANT VIEW Definition 		TO [COFIDIS2000\GRP_SQL_BILLING_SENIOR]


END /*IF*/
'

----------------------------------------------------   

-- Adiciona no Secundário os Logins
CREATE LOGIN [COFIDIS2000\GRP_SQL_ARQUITECTOS] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english];
CREATE LOGIN [COFIDIS2000\GRP_SQL_DEV_SENIOR] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english];
CREATE LOGIN [COFIDIS2000\GRP_SQL_BILLING_JUNIOR] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english];
CREATE LOGIN [COFIDIS2000\GRP_SQL_BILLING_SENIOR] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english];
--DROP LOGIN [COFIDIS2000\GRP_SQL_ARQUITECTOS]
--DROP LOGIN [COFIDIS2000\GRP_SQL_DEV_SENIOR]
--DROP LOGIN [COFIDIS2000\GRP_SQL_BILLING_JUNIOR]
--DROP LOGIN [COFIDIS2000\GRP_SQL_BILLING_SENIOR]



-- No primário agora apagar os logins

--USE [master]
--GO

--DROP LOGIN [COFIDIS2000\GRP_SQL_ARQUITECTOS]
--DROP LOGIN [COFIDIS2000\GRP_SQL_DEV_SENIOR]
--DROP LOGIN [COFIDIS2000\GRP_SQL_BILLING_JUNIOR]
--DROP LOGIN [COFIDIS2000\GRP_SQL_BILLING_SENIOR]
--GO

