/* sp_help_revlogin script 
** Generated Jul 11 2023  6:36PM on DIOMEDES */
 
 
-- Login: ##MS_PolicyTsqlExecutionLogin##
CREATE LOGIN [##MS_PolicyTsqlExecutionLogin##] WITH PASSWORD = 0x0200F7DF0092A3F3D9EBA260BDDE48F69FDD95D885AEC936B7AE4FD7E249B1E1033493B65BC3B7FF693B321843892F2FC77C5D5AD567E3E15191D6877A6E31133B3F99BAC77C HASHED, SID = 0x014EA8886B841C4CA1F7ED32489BBF62, DEFAULT_DATABASE = [master], CHECK_POLICY = ON, CHECK_EXPIRATION = OFF; ALTER LOGIN [##MS_PolicyTsqlExecutionLogin##] DISABLE
 
-- Login: NT AUTHORITY\SYSTEM
CREATE LOGIN [NT AUTHORITY\SYSTEM] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: NT SERVICE\MSSQLSERVER
CREATE LOGIN [NT SERVICE\MSSQLSERVER] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: COFIDIS2000\administrator
CREATE LOGIN [COFIDIS2000\administrator] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: NT SERVICE\SQLSERVERAGENT
CREATE LOGIN [NT SERVICE\SQLSERVERAGENT] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: COFIDIS2000\Domain Admins
CREATE LOGIN [COFIDIS2000\Domain Admins] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: COFIDIS2000\Grp Suporte Decisao
CREATE LOGIN [COFIDIS2000\Grp Suporte Decisao] FROM WINDOWS WITH DEFAULT_DATABASE = [Armada]
 
-- Login: COFIDIS2000\Grp Servico Controlo Gestao
CREATE LOGIN [COFIDIS2000\Grp Servico Controlo Gestao] FROM WINDOWS WITH DEFAULT_DATABASE = [Armada]
 
-- Login: COFIDIS2000\Grp Servico Risco Cliente
CREATE LOGIN [COFIDIS2000\Grp Servico Risco Cliente] FROM WINDOWS WITH DEFAULT_DATABASE = [Armada]
 
-- Login: COFIDIS2000\Grp Seleccoes Estudos Comerciais
CREATE LOGIN [COFIDIS2000\Grp Seleccoes Estudos Comerciais] FROM WINDOWS WITH DEFAULT_DATABASE = [Armada]
 
-- Login: COFIDIS2000\Grp Sector Administracao Sistemas
CREATE LOGIN [COFIDIS2000\Grp Sector Administracao Sistemas] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: ODBC_Diomedes
CREATE LOGIN [ODBC_Diomedes] WITH PASSWORD = 0x020098114CF401A9BD3DCD14DE63EBC98FF4AD3213567B5D9E69124F5645B00F279DD4D84E0BB4A6AD3DA116AAD988113A3FDF3FC4DBA111985A5D37A0821A48EE887182B93A HASHED, SID = 0x45E80291B36A9344AE39164EC974A1EE, DEFAULT_DATABASE = [Armada], CHECK_POLICY = OFF, CHECK_EXPIRATION = OFF
 
-- Login: COFIDIS2000\Grp Servico Controlo Acompanhamento Recuperacao
CREATE LOGIN [COFIDIS2000\Grp Servico Controlo Acompanhamento Recuperacao] FROM WINDOWS WITH DEFAULT_DATABASE = [Armada]
 
-- Login: NT SERVICE\SQLWriter
CREATE LOGIN [NT SERVICE\SQLWriter] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: NT SERVICE\winmgmt
CREATE LOGIN [NT SERVICE\winmgmt] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: ODBC_Diomedes_Hades
CREATE LOGIN [ODBC_Diomedes_Hades] WITH PASSWORD = 0x02006CAD0B0E7AF9F27B5FD8840CCDCC913736167A586D60F57C20B80AA36E46CB0DB4C9A7C98B738ECA1F02B378FDF13BEDD196EF454F9FF43DF04C7A7478EA3901DB28ABA1 HASHED, SID = 0x7659079CDE4D744C946B2B770CF327D5, DEFAULT_DATABASE = [master], CHECK_POLICY = OFF, CHECK_EXPIRATION = OFF
 
-- Login: COFIDIS2000\Grp PrevencaoSD
CREATE LOGIN [COFIDIS2000\Grp PrevencaoSD] FROM WINDOWS WITH DEFAULT_DATABASE = [master]; DENY CONNECT SQL TO [COFIDIS2000\Grp PrevencaoSD]
 
-- Login: COFIDIS2000\Grp Servico Contabilidade e Tesouraria
CREATE LOGIN [COFIDIS2000\Grp Servico Contabilidade e Tesouraria] FROM WINDOWS WITH DEFAULT_DATABASE = [Armada]
 
-- Login: COFIDIS2000\srvscvmm
CREATE LOGIN [COFIDIS2000\srvscvmm] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: COFIDIS2000\SIRINGE$
CREATE LOGIN [COFIDIS2000\SIRINGE$] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: COFIDIS2000\AGTSVC
CREATE LOGIN [COFIDIS2000\AGTSVC] FROM WINDOWS WITH DEFAULT_DATABASE = [Armada]
 
-- Login: VCADMIN
CREATE LOGIN [VCADMIN] WITH PASSWORD = 0x0200517CB1EC8ED9F798E01B787531787A4E00E1025D08A2383C905BAFAD7A25C4EECAC6A74C3482FD061DAEE430146D1795748FAF94FF351A5425A0C90FE7E30AF250B8913A HASHED, SID = 0xD798FED7EC184F44AA8571391ECEF498, DEFAULT_DATABASE = [master], CHECK_POLICY = OFF, CHECK_EXPIRATION = OFF
 
-- Login: COFIDIS2000\Grp TecOperacionalDR
CREATE LOGIN [COFIDIS2000\Grp TecOperacionalDR] FROM WINDOWS WITH DEFAULT_DATABASE = [Armada]
 
-- Login: COFIDIS2000\Grp Tecnico Controlo Actividade DR
CREATE LOGIN [COFIDIS2000\Grp Tecnico Controlo Actividade DR] FROM WINDOWS WITH DEFAULT_DATABASE = [Armada]
 
-- Login: COFIDIS2000\POWERSHELL
CREATE LOGIN [COFIDIS2000\POWERSHELL] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CDM\PIMENTCL
CREATE LOGIN [CDM\PIMENTCL] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: COFIDIS2000\Grp TO Analise
CREATE LOGIN [COFIDIS2000\Grp TO Analise] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: COFIDIS2000\SPServices_SRV_PROD
CREATE LOGIN [COFIDIS2000\SPServices_SRV_PROD] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: COFIDIS2000\sps_excel_ds
CREATE LOGIN [COFIDIS2000\sps_excel_ds] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: COFIDIS2000\sps_ss_excl
CREATE LOGIN [COFIDIS2000\sps_ss_excl] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: COFIDIS2000\Grp TecControloActividadeClientes
CREATE LOGIN [COFIDIS2000\Grp TecControloActividadeClientes] FROM WINDOWS WITH DEFAULT_DATABASE = [Armada]
 
-- Login: COFIDIS2000\Grp RespServSeguros
CREATE LOGIN [COFIDIS2000\Grp RespServSeguros] FROM WINDOWS WITH DEFAULT_DATABASE = [Armada]
 
-- Login: COFIDIS2000\Grp Captacao
CREATE LOGIN [COFIDIS2000\Grp Captacao] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: COFIDIS2000\grp estatisticas telefonia
CREATE LOGIN [COFIDIS2000\grp estatisticas telefonia] FROM WINDOWS WITH DEFAULT_DATABASE = [Armada]
 
-- Login: COFIDIS2000\Grp Setor Suporte Atividade
CREATE LOGIN [COFIDIS2000\Grp Setor Suporte Atividade] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: COFIDIS2000\grpSQLSupDecisaoPower
CREATE LOGIN [COFIDIS2000\grpSQLSupDecisaoPower] FROM WINDOWS WITH DEFAULT_DATABASE = [Armada]
 
-- Login: BUILTIN\Administrators
CREATE LOGIN [BUILTIN\Administrators] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: COFIDIS2000\Grp RespSecQualidadeProvedorCliente
CREATE LOGIN [COFIDIS2000\Grp RespSecQualidadeProvedorCliente] FROM WINDOWS WITH DEFAULT_DATABASE = [Armada]
 
-- Login: COFIDIS2000\Grp Responsaveis Serv Clientes
CREATE LOGIN [COFIDIS2000\Grp Responsaveis Serv Clientes] FROM WINDOWS WITH DEFAULT_DATABASE = [Armada]
 
-- Login: COFIDIS2000\Grp Auditoria Interna
CREATE LOGIN [COFIDIS2000\Grp Auditoria Interna] FROM WINDOWS WITH DEFAULT_DATABASE = [Armada]
 
-- Login: COFIDIS2000\Grp Direcao Sistemas Informacao
CREATE LOGIN [COFIDIS2000\Grp Direcao Sistemas Informacao] FROM WINDOWS WITH DEFAULT_DATABASE = [Armada]
 
-- Login: COFIDIS2000\Grp Sector Rentabilidade
CREATE LOGIN [COFIDIS2000\Grp Sector Rentabilidade] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: COFIDIS2000\Grp RespServAnalFuncional
CREATE LOGIN [COFIDIS2000\Grp RespServAnalFuncional] FROM WINDOWS WITH DEFAULT_DATABASE = [Armada]
 
-- Login: COFIDIS2000\grpSQLSuporteAplicacional
CREATE LOGIN [COFIDIS2000\grpSQLSuporteAplicacional] FROM WINDOWS WITH DEFAULT_DATABASE = [Armada]
 
-- Login: COFIDIS2000\Grp Helpdesk
CREATE LOGIN [COFIDIS2000\Grp Helpdesk] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: COFIDIS2000\Grp Servico Desenvolvimento de Cartoes
CREATE LOGIN [COFIDIS2000\Grp Servico Desenvolvimento de Cartoes] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: COFIDIS2000\prismasas1
CREATE LOGIN [COFIDIS2000\prismasas1] FROM WINDOWS WITH DEFAULT_DATABASE = [Armada]
 
-- Login: COFIDIS2000\Grp TecnicoControloAtividadeQualidade
CREATE LOGIN [COFIDIS2000\Grp TecnicoControloAtividadeQualidade] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: COFIDIS2000\sqlhungria
CREATE LOGIN [COFIDIS2000\sqlhungria] FROM WINDOWS WITH DEFAULT_DATABASE = [Armada]
 
-- Login: COFIDIS2000\sqleslovaquia
CREATE LOGIN [COFIDIS2000\sqleslovaquia] FROM WINDOWS WITH DEFAULT_DATABASE = [Armada]
 
-- Login: COFIDIS2000\sqlpolonia
CREATE LOGIN [COFIDIS2000\sqlpolonia] FROM WINDOWS WITH DEFAULT_DATABASE = [Armada]
 
-- Login: CDM\COUTINRA
CREATE LOGIN [CDM\COUTINRA] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: COFIDIS2000\AGTSVC_24DW
CREATE LOGIN [COFIDIS2000\AGTSVC_24DW] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: COFIDIS2000\grpSQLtoRiskManagement
CREATE LOGIN [COFIDIS2000\grpSQLtoRiskManagement] FROM WINDOWS WITH DEFAULT_DATABASE = [Armada]
 
-- Login: CDM\costaco
CREATE LOGIN [CDM\costaco] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: COFIDIS2000\PIRS_SVC_UNN
CREATE LOGIN [COFIDIS2000\PIRS_SVC_UNN] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: COFIDIS2000\Grp TO SCL
CREATE LOGIN [COFIDIS2000\Grp TO SCL] FROM WINDOWS WITH DEFAULT_DATABASE = [Armada]
 
-- Login: COFIDIS2000\Grp Analista Mercado
CREATE LOGIN [COFIDIS2000\Grp Analista Mercado] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: COFIDIS2000\tfsrelease
CREATE LOGIN [COFIDIS2000\tfsrelease] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: COFIDIS2000\Grp Sector Contabilidade Clientes Reporte
CREATE LOGIN [COFIDIS2000\Grp Sector Contabilidade Clientes Reporte] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: COFIDIS2000\grpSQLSeguros
CREATE LOGIN [COFIDIS2000\grpSQLSeguros] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: COFIDIS2000\Grp SQL_DBA_Prod
CREATE LOGIN [COFIDIS2000\Grp SQL_DBA_Prod] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CDM\MARQUESL
CREATE LOGIN [CDM\MARQUESL] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: COFIDIS2000\grpSQLGrowthMarketing
CREATE LOGIN [COFIDIS2000\grpSQLGrowthMarketing] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: COFIDIS2000\Grp Servico Dados e Modelos
CREATE LOGIN [COFIDIS2000\Grp Servico Dados e Modelos] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CDM\RAMALHLA
CREATE LOGIN [CDM\RAMALHLA] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: COFIDIS2000\grpSQLSCAO
CREATE LOGIN [COFIDIS2000\grpSQLSCAO] FROM WINDOWS WITH DEFAULT_DATABASE = [Armada]
 
-- Login: CDM\NOGUEIDA
CREATE LOGIN [CDM\NOGUEIDA] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CDM\goncalam
CREATE LOGIN [CDM\goncalam] FROM WINDOWS WITH DEFAULT_DATABASE = [TaskForce]
 
-- Login: COFIDIS2000\Grp CODI
CREATE LOGIN [COFIDIS2000\Grp CODI] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: COFIDIS2000\Grp Servico Controlo e Acompanhamentos das Operacoes
CREATE LOGIN [COFIDIS2000\Grp Servico Controlo e Acompanhamentos das Operacoes] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: COFIDIS2000\Grp Responsaveis Servico
CREATE LOGIN [COFIDIS2000\Grp Responsaveis Servico] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CDM\SINTRAAN
CREATE LOGIN [CDM\SINTRAAN] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: COFIDIS2000\GrpBillingDecisional
CREATE LOGIN [COFIDIS2000\GrpBillingDecisional] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: COFIDIS2000\GrpSqlDadosModelosXselling
CREATE LOGIN [COFIDIS2000\GrpSqlDadosModelosXselling] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: COFIDIS2000\Grp RespSecRentabilidade
CREATE LOGIN [COFIDIS2000\Grp RespSecRentabilidade] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: COFIDIS2000\SQLContab_cliente_reporte
CREATE LOGIN [COFIDIS2000\SQLContab_cliente_reporte] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: COFIDIS2000\GrpBillingSqlNivel2
CREATE LOGIN [COFIDIS2000\GrpBillingSqlNivel2] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CDM\FILIPEVA
CREATE LOGIN [CDM\FILIPEVA] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: COFIDIS2000\Grp Risk Management Protecao Dados
CREATE LOGIN [COFIDIS2000\Grp Risk Management Protecao Dados] FROM WINDOWS WITH DEFAULT_DATABASE = [Armada]
 
-- Login: CDM\CORDEIPA
CREATE LOGIN [CDM\CORDEIPA] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: COFIDIS2000\GrpBillingGestoresTranfs
CREATE LOGIN [COFIDIS2000\GrpBillingGestoresTranfs] FROM WINDOWS WITH DEFAULT_DATABASE = [Armada]
 
-- Login: CDM\OLIVEIGE
CREATE LOGIN [CDM\OLIVEIGE] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: COFIDIS2000\SQLgrpProjectoKPI
CREATE LOGIN [COFIDIS2000\SQLgrpProjectoKPI] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: COFIDIS2000\grpSQLServiçoAcompanhamentoActividade
CREATE LOGIN [COFIDIS2000\grpSQLServiçoAcompanhamentoActividade] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: COFIDIS2000\grpSQLDirComercial
CREATE LOGIN [COFIDIS2000\grpSQLDirComercial] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: COFIDIS2000\grpsqlcomissoes
CREATE LOGIN [COFIDIS2000\grpsqlcomissoes] FROM WINDOWS WITH DEFAULT_DATABASE = [Armada]
 
-- Login: COFIDIS2000\Grp Controlo Permanente e Conformidade
CREATE LOGIN [COFIDIS2000\Grp Controlo Permanente e Conformidade] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: COFIDIS2000\grp sector contabilidade geral fiscalidade
CREATE LOGIN [COFIDIS2000\grp sector contabilidade geral fiscalidade] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CDM\almeidda
CREATE LOGIN [CDM\almeidda] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CDM\NOGUEIPA
CREATE LOGIN [CDM\NOGUEIPA] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CDM\gomesne
CREATE LOGIN [CDM\gomesne] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: lnk_caliope
CREATE LOGIN [lnk_caliope] WITH PASSWORD = 0x0200D7672DCC690A13460891D3D277C83C535901657901297CCD633BB998D947AD3305D3FC04BC5AD08EE225B783D7B632A8F271039141AC8FF3641D64A1AE77B388E9E10785 HASHED, SID = 0x2131994F5F236D4D934D3C5D21EDE436, DEFAULT_DATABASE = [master], CHECK_POLICY = OFF, CHECK_EXPIRATION = OFF
 
-- Login: COFIDIS2000\grpSQLSetorMarkIntelInov
CREATE LOGIN [COFIDIS2000\grpSQLSetorMarkIntelInov] FROM WINDOWS WITH DEFAULT_DATABASE = [Armada]
 
-- Login: cdm\rodrigcf
CREATE LOGIN [cdm\rodrigcf] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: COFIDIS2000\grpSQLsrvMonitoriSuportComercial
CREATE LOGIN [COFIDIS2000\grpSQLsrvMonitoriSuportComercial] FROM WINDOWS WITH DEFAULT_DATABASE = [Armada]
 
-- Login: CDM\jesussa
CREATE LOGIN [CDM\jesussa] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CDM\LUISSA
CREATE LOGIN [CDM\LUISSA] FROM WINDOWS WITH DEFAULT_DATABASE = [TaskForce]
 
-- Login: COFIDIS2000\Grp Sector Multicanal Auto
CREATE LOGIN [COFIDIS2000\Grp Sector Multicanal Auto] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CDM\OLIVEIPE
CREATE LOGIN [CDM\OLIVEIPE] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: COFIDIS2000\GRP_Diomedes-CC360
CREATE LOGIN [COFIDIS2000\GRP_Diomedes-CC360] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CDM\COSTAPE
CREATE LOGIN [CDM\COSTAPE] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CDM\GAUDENPU
CREATE LOGIN [CDM\GAUDENPU] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CDM\CAEIROHU
CREATE LOGIN [CDM\CAEIROHU] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CDM\BRASILCA
CREATE LOGIN [CDM\BRASILCA] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CDM\DAVIDSO
CREATE LOGIN [CDM\DAVIDSO] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CDM\SILVASO
CREATE LOGIN [CDM\SILVASO] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CDM\GOMESNA
CREATE LOGIN [CDM\GOMESNA] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CDM\MARIANAL
CREATE LOGIN [CDM\MARIANAL] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CDM\VERISSDE
CREATE LOGIN [CDM\VERISSDE] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CDM\JOAOSE
CREATE LOGIN [CDM\JOAOSE] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CDM\SILVAIV
CREATE LOGIN [CDM\SILVAIV] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: grafana_readonly
CREATE LOGIN [grafana_readonly] WITH PASSWORD = 0x0200C524830B4625648480FE29050C6E0AFAA284557FDB39746A089C50082A983C5C17D63EB0173B92A192B1E0BFE9B18298EFB704DF77487E92CD2F3430F950877F05AE0DF9 HASHED, SID = 0xE17BB8F4303DC54AA097A1E2DA2B9A0C, DEFAULT_DATABASE = [Armada], CHECK_POLICY = OFF, CHECK_EXPIRATION = OFF
 
-- Login: CDM\TELESAL
CREATE LOGIN [CDM\TELESAL] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CDM\GOULAOMA
CREATE LOGIN [CDM\GOULAOMA] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CDM\CORREITE
CREATE LOGIN [CDM\CORREITE] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: COFIDIS2000\Grp Gestao Pessoal
CREATE LOGIN [COFIDIS2000\Grp Gestao Pessoal] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: COFIDIS2000\mnico
CREATE LOGIN [COFIDIS2000\mnico] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: COFIDIS2000\Grp Servico Auditoria Interna
CREATE LOGIN [COFIDIS2000\Grp Servico Auditoria Interna] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: COFIDIS2000\Grp Sector Operational Inteligence
CREATE LOGIN [COFIDIS2000\Grp Sector Operational Inteligence] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: COFIDIS2000\Grp Setor Marketing Intelligence & Innovation
CREATE LOGIN [COFIDIS2000\Grp Setor Marketing Intelligence & Innovation] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CDM\MOURATAN
CREATE LOGIN [CDM\MOURATAN] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: COFIDIS2000\Grp Servico Risk Management Read
CREATE LOGIN [COFIDIS2000\Grp Servico Risk Management Read] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CDM\CARVALSU
CREATE LOGIN [CDM\CARVALSU] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CDM\GARCIAA1
CREATE LOGIN [CDM\GARCIAA1] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CDM\LDF38CONTGEST
CREATE LOGIN [CDM\LDF38CONTGEST] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: COFIDIS2000\grpformacaosql
CREATE LOGIN [COFIDIS2000\grpformacaosql] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CDM\MUGEIRDA
CREATE LOGIN [CDM\MUGEIRDA] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CDM\FONTESJO
CREATE LOGIN [CDM\FONTESJO] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CDM\JACINTMF
CREATE LOGIN [CDM\JACINTMF] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: COFIDIS2000\Grp Servico Monitorizacao e Suporte Comercial
CREATE LOGIN [COFIDIS2000\Grp Servico Monitorizacao e Suporte Comercial] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: api_modeloretencao
CREATE LOGIN [api_modeloretencao] WITH PASSWORD = 0x020059FAE397300E5BD4D8A844A330DA308E48037016E9280AEFE3539900A31FF11CE8D089A8495318637A083ED4FA36A02332975466E2FDB5B581774ED29DBC2A3E9CD59A10 HASHED, SID = 0x0D7E4A89EC32C243A898C0C94191ABA3, DEFAULT_DATABASE = [Armada], CHECK_POLICY = OFF, CHECK_EXPIRATION = OFF
 
-- Login: CDM\VEIGAIN
CREATE LOGIN [CDM\VEIGAIN] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CDM\BROEGALU
CREATE LOGIN [CDM\BROEGALU] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CDM\domingrc
CREATE LOGIN [CDM\domingrc] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CDM\FERROVE
CREATE LOGIN [CDM\FERROVE] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CDM\MARTINT4
CREATE LOGIN [CDM\MARTINT4] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CDM\PACIENSA
CREATE LOGIN [CDM\PACIENSA] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CDM\LADEIRDI
CREATE LOGIN [CDM\LADEIRDI] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CDM\MARQUEVA
CREATE LOGIN [CDM\MARQUEVA] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: COFIDIS2000\Grp RespServDesCaptacao
CREATE LOGIN [COFIDIS2000\Grp RespServDesCaptacao] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CDM\SEGISMTE
CREATE LOGIN [CDM\SEGISMTE] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CDM\SANTOSHE
CREATE LOGIN [CDM\SANTOSHE] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: api_insurancebylicenseplate
CREATE LOGIN [api_insurancebylicenseplate] WITH PASSWORD = 0x02006FC27C5792778A07DAFBBE196889B1AE96C58CF97411EDC55ECB555AB06F200E70DEAE6F3772B139B5111FD36B0C050EE71DE9CFDB08204B5FFA648129815B7816C19081 HASHED, SID = 0xE2EE64BABED4C547B0D82727A8068D9E, DEFAULT_DATABASE = [Armada], CHECK_POLICY = OFF, CHECK_EXPIRATION = OFF
 
-- Login: COFIDIS2000\cofptpsqldba01-mon
CREATE LOGIN [COFIDIS2000\cofptpsqldba01-mon] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CDM\ROSAPE
CREATE LOGIN [CDM\ROSAPE] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CDM\FRANCORR
CREATE LOGIN [CDM\FRANCORR] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CDM\LINHARFE
CREATE LOGIN [CDM\LINHARFE] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CDM\AZEVEDJA
CREATE LOGIN [CDM\AZEVEDJA] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CDM\GOMESHE
CREATE LOGIN [CDM\GOMESHE] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: COFIDIS2000\Grp Sector Tesouraria
CREATE LOGIN [COFIDIS2000\Grp Sector Tesouraria] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: COFIDIS2000\Grp Responsaveis Onboarding
CREATE LOGIN [COFIDIS2000\Grp Responsaveis Onboarding] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: cofidis2000\prd_apicontperm
CREATE LOGIN [cofidis2000\prd_apicontperm] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: prod_insurance_cofidisapi
CREATE LOGIN [prod_insurance_cofidisapi] WITH PASSWORD = 0x0200EB084794864DA9B0B70CE1D9F1D462492883492DEF15108E81DEDC921E6426E6E0D6E238C57EAAE33C7C44F7E302C686A5E46130A69789D7B5976F258A761BB6AAF7A037 HASHED, SID = 0xFA46AEB2DFFFB040AAE168E21D8C7D3A, DEFAULT_DATABASE = [master], CHECK_POLICY = ON, CHECK_EXPIRATION = OFF
 
-- Login: COFIDIS2000\Grp Sector Analise Funcional
CREATE LOGIN [COFIDIS2000\Grp Sector Analise Funcional] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: COFIDIS2000\GrpSQLSetorContenciosoExterno
CREATE LOGIN [COFIDIS2000\GrpSQLSetorContenciosoExterno] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CDM\juniorse
CREATE LOGIN [CDM\juniorse] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CDM\bentobr
CREATE LOGIN [CDM\bentobr] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CDM\alvesda
CREATE LOGIN [CDM\alvesda] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: CDM\MIRANMA
CREATE LOGIN [CDM\MIRANMA] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: PROD_SRV_PREVCHMSCL
CREATE LOGIN [PROD_SRV_PREVCHMSCL] WITH PASSWORD = 0x02006C0189A5B670201A296005676A9A7A73B79CC5CD63F46B5042681F1960DFDAE60F7A5C4CE5500926EC625569E52438C89C2997A635FE0D84D7348DE9050C8FCC7CFDCAD3 HASHED, SID = 0x4840C30F0173F94EA0ACE12BE3EABD8A, DEFAULT_DATABASE = [master], CHECK_POLICY = ON, CHECK_EXPIRATION = OFF
 
-- Login: COFIDIS2000\GRP_SQL_DADOS_MODELOS_PREV
CREATE LOGIN [COFIDIS2000\GRP_SQL_DADOS_MODELOS_PREV] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: ##MS_PolicyEventProcessingLogin##
CREATE LOGIN [##MS_PolicyEventProcessingLogin##] WITH PASSWORD = 0x020013AB4B049663893EC6267498D3543746F9C18E6C6FA3CECCCD7A090EB6F48784829F0B2877C27D76D853513082A44CDF774A35167D6F5151CC0D0A2A94F5E1DA345876CF HASHED, SID = 0x93FFE78C2F539F41B01F0B011C8F6B1C, DEFAULT_DATABASE = [master], CHECK_POLICY = ON, CHECK_EXPIRATION = OFF; ALTER LOGIN [##MS_PolicyEventProcessingLogin##] DISABLE
 
-- Login: prod_api_modeloretencao
CREATE LOGIN [prod_api_modeloretencao] WITH PASSWORD = 0x02006B64B862F6BBFDC296B48C7A5711DEDE3318F47B81A73B04ECF92E87CDE33E7A6E2AB49B793E91EF7A67CC4BC0F667C7377CCCB5558B8B7DFBB24D83EAAB79034FB6EFAF HASHED, SID = 0x61B52EB11215634A91A599818E4DFE99, DEFAULT_DATABASE = [master], CHECK_POLICY = ON, CHECK_EXPIRATION = OFF
 
-- Login: CDM\ANTONIDN
CREATE LOGIN [CDM\ANTONIDN] FROM WINDOWS WITH DEFAULT_DATABASE = [master]

Completion time: 2023-07-11T18:36:49.6528685+01:00
