

GRANT SELECT,INSERT, UPDATE,DELETE  ON SCHEMA::cgest TO [COFIDIS2000\GRP_SQL_DADOS_MODELOS];
GRANT SELECT ON SCHEMA::cgest TO [ODBC_Diomedes_Hades];
GRANT SELECT ON SCHEMA::cgest TO [Cofidis2000\GrpDataAnalytics006];