-- PRD - DIOMEDES
-- PREVENCAO
--  COFIDIS2000\GRP_SQL_DADOS_MODELOS_PREV


use master
go
IF EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_DADOS_MODELOS_PREV')
     DROP LOGIN [COFIDIS2000\GRP_SQL_DADOS_MODELOS_PREV];
GO  

IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_DADOS_MODELOS_PREV')
     CREATE LOGIN [COFIDIS2000\GRP_SQL_DADOS_MODELOS_PREV] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english];
GO    


EXEC sp_MSforeachdb '
IF ''?'' NOT IN (''master'', ''model'', ''msdb'', ''SSISDB'', ''tempdb''
,''dba_db''

) 
BEGIN 
    USE [?]
    PRINT ''?''
	DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_DADOS_MODELOS_PREV]

    IF DATABASE_PRINCIPAL_ID(''COFIDIS2000\GRP_SQL_DADOS_MODELOS_PREV'') IS NULL
    BEGIN
        PRINT '' Criando o user.''
        CREATE USER [COFIDIS2000\GRP_SQL_DADOS_MODELOS_PREV] FROM LOGIN [COFIDIS2000\GRP_SQL_DADOS_MODELOS_PREV];
    END /*IF*/
    PRINT '' Adicionar as permissões para o user ...''
	GRANT CONNECT TO [COFIDIS2000\GRP_SQL_DADOS_MODELOS_PREV]
	
	
	GRANT SELECT, INSERT, UPDATE TO [COFIDIS2000\GRP_SQL_DADOS_MODELOS_PREV] 
	GRANT ALTER 				TO [COFIDIS2000\GRP_SQL_DADOS_MODELOS_PREV]
	GRANT VIEW Definition 		TO [COFIDIS2000\GRP_SQL_DADOS_MODELOS_PREV]
	GRANT EXECUTE 				TO [COFIDIS2000\GRP_SQL_DADOS_MODELOS_PREV]
	GRANT SHOWPLAN 				TO [COFIDIS2000\GRP_SQL_DADOS_MODELOS_PREV]


END /*IF*/
'




/*
--Privilégios MSDB
*/
USE [msdb]
GO
DROP SCHEMA IF EXISTS [COFIDIS2000\GRP_SQL_DADOS_MODELOS_PREV]
DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_DADOS_MODELOS_PREV]
go
IF NOT EXISTS (SELECT NAME FROM sys.database_principals WHERE NAME =  'COFIDIS2000\GRP_SQL_DADOS_MODELOS_PREV') BEGIN CREATE USER  [COFIDIS2000\GRP_SQL_DADOS_MODELOS_PREV] 
   FOR LOGIN [COFIDIS2000\GRP_SQL_DADOS_MODELOS_PREV] END ELSE ALTER USER  [COFIDIS2000\GRP_SQL_DADOS_MODELOS_PREV] WITH LOGIN = [COFIDIS2000\GRP_SQL_DADOS_MODELOS_PREV];
IF DATABASE_PRINCIPAL_ID('COFIDIS2000\GRP_SQL_DADOS_MODELOS_PREV') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\GRP_SQL_DADOS_MODELOS_PREV]





use master
go
GRANT ALTER ANY CONNECTION TO [COFIDIS2000\GRP_SQL_DADOS_MODELOS_PREV];
GRANT ALTER ANY connection TO [COFIDIS2000\GRP_SQL_DADOS_MODELOS_PREV] 
GO

/*
exec sp_addrolemember 'SQLAgentReaderRole', 'COFIDIS2000\GRP_SQL_DADOS_MODELOS_PREV'
exec sp_addrolemember 'SQLAgentUserRole', 'COFIDIS2000\GRP_SQL_DADOS_MODELOS_PREV'
exec sp_addrolemember 'SQLAgentOperatorRole', 'COFIDIS2000\GRP_SQL_DADOS_MODELOS_PREV'
exec sp_addrolemember 'db_ssisadmin', 'COFIDIS2000\GRP_SQL_DADOS_MODELOS_PREV'
exec sp_addrolemember 'db_datareader', 'COFIDIS2000\GRP_SQL_DADOS_MODELOS_PREV'
exec sp_addrolemember 'db_datawriter', 'COFIDIS2000\GRP_SQL_DADOS_MODELOS_PREV'
exec sp_addrolemember 'db_ddladmin', 'COFIDIS2000\GRP_SQL_DADOS_MODELOS_PREV'


*/
