-- DEV - Suporte Aplicacional
--  COFIDIS2000\GRP_SQL_DADOS_MODELOS
--

use master
go
IF EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_DADOS_MODELOS')
     DROP LOGIN [COFIDIS2000\GRP_SQL_DADOS_MODELOS];
GO  

IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_DADOS_MODELOS')
     CREATE LOGIN [COFIDIS2000\GRP_SQL_DADOS_MODELOS] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english];
GO    


EXEC sp_MSforeachdb '
IF ''?'' NOT IN (''master'', ''model'', ''msdb'', ''SSISDB'', ''tempdb''
,''AdministracaoSistemas''

) 
BEGIN 
    USE [?]
    PRINT ''?''
	DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_DADOS_MODELOS]

    IF DATABASE_PRINCIPAL_ID(''COFIDIS2000\GRP_SQL_DADOS_MODELOS'') IS NULL
    BEGIN
        PRINT '' Criando o user.''
        CREATE USER [COFIDIS2000\GRP_SQL_DADOS_MODELOS] FROM LOGIN [COFIDIS2000\GRP_SQL_DADOS_MODELOS];
    END /*IF*/
    PRINT '' Adicionar as permissões para o user ...''
	GRANT CONNECT TO [COFIDIS2000\GRP_SQL_DADOS_MODELOS]
	GRANT SELECT				 TO [COFIDIS2000\GRP_SQL_DADOS_MODELOS] 
	GRANT VIEW Definition 		TO [COFIDIS2000\GRP_SQL_DADOS_MODELOS]
	GRANT EXECUTE 				TO [COFIDIS2000\GRP_SQL_DADOS_MODELOS]
	GRANT SHOWPLAN 				TO [COFIDIS2000\GRP_SQL_DADOS_MODELOS]

END /*IF*/
'


/*
--Privilégios MSDB
*/
USE [msdb]
GO
DROP SCHEMA IF EXISTS [COFIDIS2000\GRP_SQL_DADOS_MODELOS]
DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_DADOS_MODELOS]
go
IF NOT EXISTS (SELECT NAME FROM sys.database_principals WHERE NAME =  'COFIDIS2000\GRP_SQL_DADOS_MODELOS') BEGIN CREATE USER  [COFIDIS2000\GRP_SQL_DADOS_MODELOS] 
   FOR LOGIN [COFIDIS2000\GRP_SQL_DADOS_MODELOS] END ELSE ALTER USER  [COFIDIS2000\GRP_SQL_DADOS_MODELOS] WITH LOGIN = [COFIDIS2000\GRP_SQL_DADOS_MODELOS];
IF DATABASE_PRINCIPAL_ID('COFIDIS2000\GRP_SQL_DADOS_MODELOS') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\GRP_SQL_DADOS_MODELOS]

exec sp_addrolemember 'SQLAgentOperatorRole', 'COFIDIS2000\GRP_SQL_DEV_SENIOR'
exec sp_addrolemember 'db_ssisoperator', 'COFIDIS2000\GRP_SQL_DADOS_MODELOS'
exec sp_addrolemember 'db_datareader', 'COFIDIS2000\GRP_SQL_DADOS_MODELOS'

/*
--Privilégios SSISDB
*/
USE [SSISDB]
GO
DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_DADOS_MODELOS]
go
IF NOT EXISTS (SELECT NAME FROM sys.database_principals WHERE NAME =  'COFIDIS2000\GRP_SQL_DADOS_MODELOS') BEGIN CREATE USER  [COFIDIS2000\GRP_SQL_DADOS_MODELOS] 
   FOR LOGIN [COFIDIS2000\GRP_SQL_DADOS_MODELOS] END ELSE ALTER USER  [COFIDIS2000\GRP_SQL_DADOS_MODELOS] WITH LOGIN = [COFIDIS2000\GRP_SQL_DADOS_MODELOS];
IF DATABASE_PRINCIPAL_ID('COFIDIS2000\GRP_SQL_DADOS_MODELOS') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\GRP_SQL_DADOS_MODELOS]

ALTER ROLE [db_datareader] ADD MEMBER [COFIDIS2000\GRP_SQL_DADOS_MODELOS]
GO
ALTER ROLE [ssis_logreader] ADD MEMBER [COFIDIS2000\GRP_SQL_DADOS_MODELOS]
GO

-- UAT - Arquitectos
--  COFIDIS2000\GRP_SQL_ARQUITECTOS
--

use master
go
IF EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_ARQUITECTOS')
     DROP LOGIN [COFIDIS2000\GRP_SQL_ARQUITECTOS];
GO  

IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_ARQUITECTOS')
     CREATE LOGIN [COFIDIS2000\GRP_SQL_ARQUITECTOS] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english];
GO    


EXEC sp_MSforeachdb '
IF ''?'' NOT IN (''master'', ''model'', ''msdb'', ''SSISDB'', ''tempdb''
,''AdministracaoSistemas''




) 
BEGIN 
    USE [?]
    PRINT ''?''
	DROP SCHEMA IF EXISTS [COFIDIS2000\GRP_SQL_ARQUITECTOS]
	DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_ARQUITECTOS]

    IF DATABASE_PRINCIPAL_ID(''COFIDIS2000\GRP_SQL_ARQUITECTOS'') IS NULL
    BEGIN
        PRINT '' Criando o user.''
        CREATE USER [COFIDIS2000\GRP_SQL_ARQUITECTOS] FROM LOGIN [COFIDIS2000\GRP_SQL_ARQUITECTOS];
    END /*IF*/
    PRINT '' Adicionar as permissões para o user ...''
	GRANT CONNECT TO [COFIDIS2000\GRP_SQL_ARQUITECTOS]
	GRANT SELECT                TO [COFIDIS2000\GRP_SQL_ARQUITECTOS] 
	GRANT VIEW Definition 		TO [COFIDIS2000\GRP_SQL_ARQUITECTOS]
	GRANT EXECUTE 				TO [COFIDIS2000\GRP_SQL_ARQUITECTOS]
	GRANT SHOWPLAN 				TO [COFIDIS2000\GRP_SQL_ARQUITECTOS]

END /*IF*/
'


/*
--Privilégios MSDB
*/
USE [msdb]
GO
DROP SCHEMA IF EXISTS [COFIDIS2000\GRP_SQL_ARQUITECTOS]
DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_ARQUITECTOS]
go
IF NOT EXISTS (SELECT NAME FROM sys.database_principals WHERE NAME =  'COFIDIS2000\GRP_SQL_ARQUITECTOS') BEGIN CREATE USER  [COFIDIS2000\GRP_SQL_ARQUITECTOS] 
   FOR LOGIN [COFIDIS2000\GRP_SQL_ARQUITECTOS] END ELSE ALTER USER  [COFIDIS2000\GRP_SQL_ARQUITECTOS] WITH LOGIN = [COFIDIS2000\GRP_SQL_ARQUITECTOS];
IF DATABASE_PRINCIPAL_ID('COFIDIS2000\GRP_SQL_ARQUITECTOS') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\GRP_SQL_ARQUITECTOS]

exec sp_addrolemember 'SQLAgentOperatorRole', 'COFIDIS2000\GRP_SQL_ARQUITECTOS'
exec sp_addrolemember 'db_ssisoperator', 'COFIDIS2000\GRP_SQL_ARQUITECTOS'
exec sp_addrolemember 'db_ssisltduser', 'COFIDIS2000\GRP_SQL_ARQUITECTOS'
exec sp_addrolemember 'db_datareader', 'COFIDIS2000\GRP_SQL_ARQUITECTOS'

/*
--Privilégios SSISDB
*/
USE [SSISDB]
GO
DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_ARQUITECTOS]
go
IF NOT EXISTS (SELECT NAME FROM sys.database_principals WHERE NAME =  'COFIDIS2000\GRP_SQL_ARQUITECTOS') BEGIN CREATE USER  [COFIDIS2000\GRP_SQL_ARQUITECTOS] 
   FOR LOGIN [COFIDIS2000\GRP_SQL_ARQUITECTOS] END ELSE ALTER USER  [COFIDIS2000\GRP_SQL_ARQUITECTOS] WITH LOGIN = [COFIDIS2000\GRP_SQL_ARQUITECTOS];
IF DATABASE_PRINCIPAL_ID('COFIDIS2000\GRP_SQL_ARQUITECTOS') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\GRP_SQL_ARQUITECTOS]

ALTER ROLE [db_datareader] ADD MEMBER [COFIDIS2000\GRP_SQL_ARQUITECTOS]
GO
ALTER ROLE [ssis_logreader] ADD MEMBER [COFIDIS2000\GRP_SQL_ARQUITECTOS]
GO



---
-- UAT - SENIORES
--  COFIDIS2000\GRP_SQL_DEV_SENIOR
--

use master
go
IF EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_DEV_SENIOR')
     DROP LOGIN [COFIDIS2000\GRP_SQL_DEV_SENIOR];
GO  

IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_DEV_SENIOR')
     CREATE LOGIN [COFIDIS2000\GRP_SQL_DEV_SENIOR] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english];
GO    


EXEC sp_MSforeachdb '
IF ''?'' NOT IN (''master'', ''model'', ''msdb'', ''SSISDB'', ''tempdb''
,''AdministracaoSistemas''
) 
BEGIN 
    USE [?]
    PRINT ''?''
	DROP SCHEMA IF EXISTS [COFIDIS2000\GRP_SQL_DEV_SENIOR]
	DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_DEV_SENIOR]

    IF DATABASE_PRINCIPAL_ID(''COFIDIS2000\GRP_SQL_DEV_SENIOR'') IS NULL
    BEGIN
        PRINT '' Criando o user.''
        CREATE USER [COFIDIS2000\GRP_SQL_DEV_SENIOR] FROM LOGIN [COFIDIS2000\GRP_SQL_DEV_SENIOR];
    END /*IF*/
    PRINT '' Adicionar as permissões para o user ...''
	GRANT CONNECT TO [COFIDIS2000\GRP_SQL_DEV_SENIOR]
	GRANT SELECT TO [COFIDIS2000\GRP_SQL_DEV_SENIOR] 
	GRANT VIEW Definition 		TO [COFIDIS2000\GRP_SQL_DEV_SENIOR]
	GRANT EXECUTE 				TO [COFIDIS2000\GRP_SQL_DEV_SENIOR]
	GRANT SHOWPLAN 				TO [COFIDIS2000\GRP_SQL_DEV_SENIOR]

END /*IF*/
'


/*
--Privilégios MSDB
*/
USE [msdb]
GO
DROP SCHEMA IF EXISTS [COFIDIS2000\GRP_SQL_DEV_SENIOR]
DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_DEV_SENIOR]
go
IF NOT EXISTS (SELECT NAME FROM sys.database_principals WHERE NAME =  'COFIDIS2000\GRP_SQL_DEV_SENIOR') BEGIN CREATE USER  [COFIDIS2000\GRP_SQL_DEV_SENIOR] 
   FOR LOGIN [COFIDIS2000\GRP_SQL_DEV_SENIOR] END ELSE ALTER USER  [COFIDIS2000\GRP_SQL_DEV_SENIOR] WITH LOGIN = [COFIDIS2000\GRP_SQL_DEV_SENIOR];
IF DATABASE_PRINCIPAL_ID('COFIDIS2000\GRP_SQL_DEV_SENIOR') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\GRP_SQL_DEV_SENIOR]

exec sp_addrolemember 'SQLAgentOperatorRole', 'COFIDIS2000\GRP_SQL_DEV_SENIOR'
exec sp_addrolemember 'db_ssisoperator', 'COFIDIS2000\GRP_SQL_DEV_SENIOR'
exec sp_addrolemember 'db_ssisltduser', 'COFIDIS2000\GRP_SQL_DEV_SENIOR'
exec sp_addrolemember 'db_datareader', 'COFIDIS2000\GRP_SQL_DEV_SENIOR'

/*
--Privilégios SSISDB
*/
USE [SSISDB]
GO
DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_DEV_SENIOR]
go
IF NOT EXISTS (SELECT NAME FROM sys.database_principals WHERE NAME =  'COFIDIS2000\GRP_SQL_DEV_SENIOR') BEGIN CREATE USER  [COFIDIS2000\GRP_SQL_DEV_SENIOR] 
   FOR LOGIN [COFIDIS2000\GRP_SQL_DEV_SENIOR] END ELSE ALTER USER  [COFIDIS2000\GRP_SQL_DEV_SENIOR] WITH LOGIN = [COFIDIS2000\GRP_SQL_DEV_SENIOR];
IF DATABASE_PRINCIPAL_ID('COFIDIS2000\GRP_SQL_DEV_SENIOR') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\GRP_SQL_DEV_SENIOR]

ALTER ROLE [db_datareader] ADD MEMBER [COFIDIS2000\GRP_SQL_DEV_SENIOR]
GO
ALTER ROLE [ssis_logreader] ADD MEMBER [COFIDIS2000\GRP_SQL_DEV_SENIOR]
GO

-- 	GRANT ALTER 				TO [COFIDIS2000\GRP_SQL_DEV_SENIOR]
--
-- SIT - DEV Tecnico
--  COFIDIS2000\GRP_SQL_DEV_TECNICO
--

use master
go
IF EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_DEV_TECNICO')
     DROP LOGIN [COFIDIS2000\GRP_SQL_DEV_TECNICO];
GO  

IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_DEV_TECNICO')
     CREATE LOGIN [COFIDIS2000\GRP_SQL_DEV_TECNICO] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english];
GO    


EXEC sp_MSforeachdb '
IF ''?'' NOT IN (''master'', ''model'', ''msdb'', ''SSISDB'', ''tempdb''

,''ACCIPIENS''
,''AdministracaoSistemas''
,''m-it2008''
,''cofcc_awdb''
,''cofcc_hds''
,''Insurance''
,''LCM''
,''LCMReports''
,''QUAContactCenter360''
,''RH''


) 
BEGIN 
    USE [?]
    PRINT ''?''
	DROP SCHEMA IF EXISTS [COFIDIS2000\GRP_SQL_DEV_TECNICO]
	DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_DEV_TECNICO]

    IF DATABASE_PRINCIPAL_ID(''COFIDIS2000\GRP_SQL_DEV_TECNICO'') IS NULL
    BEGIN
        PRINT '' Criando o user.''
        CREATE USER [COFIDIS2000\GRP_SQL_DEV_TECNICO] FROM LOGIN [COFIDIS2000\GRP_SQL_DEV_TECNICO];
    END /*IF*/
    PRINT '' Adicionar as permissões para o user ...''
	GRANT CONNECT TO [COFIDIS2000\GRP_SQL_DEV_TECNICO]
	GRANT SELECT  TO [COFIDIS2000\GRP_SQL_DEV_TECNICO] 
	GRANT VIEW Definition 		TO [COFIDIS2000\GRP_SQL_DEV_TECNICO]
	GRANT EXECUTE 				TO [COFIDIS2000\GRP_SQL_DEV_TECNICO]
	GRANT SHOWPLAN 				TO [COFIDIS2000\GRP_SQL_DEV_TECNICO]

END /*IF*/
'


/*
--Privilégios MSDB
*/
USE [msdb]
GO
DROP SCHEMA IF EXISTS [COFIDIS2000\GRP_SQL_DEV_TECNICO]
DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_DEV_TECNICO]
go
IF NOT EXISTS (SELECT NAME FROM sys.database_principals WHERE NAME =  'COFIDIS2000\GRP_SQL_DEV_TECNICO') BEGIN CREATE USER  [COFIDIS2000\GRP_SQL_DEV_TECNICO] 
   FOR LOGIN [COFIDIS2000\GRP_SQL_DEV_TECNICO] END ELSE ALTER USER  [COFIDIS2000\GRP_SQL_DEV_TECNICO] WITH LOGIN = [COFIDIS2000\GRP_SQL_DEV_TECNICO];
IF DATABASE_PRINCIPAL_ID('COFIDIS2000\GRP_SQL_DEV_TECNICO') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\GRP_SQL_DEV_TECNICO]

exec sp_addrolemember 'SQLAgentOperatorRole', 'COFIDIS2000\GRP_SQL_DEV_TECNICO'
exec sp_addrolemember 'db_ssisoperator', 'COFIDIS2000\GRP_SQL_DEV_TECNICO'
exec sp_addrolemember 'db_ssisltduser', 'COFIDIS2000\GRP_SQL_DEV_TECNICO'
exec sp_addrolemember 'db_datareader', 'COFIDIS2000\GRP_SQL_DEV_TECNICO'

/*
--Privilégios SSISDB
*/
USE [SSISDB]
GO
DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_DEV_TECNICO]
go
IF NOT EXISTS (SELECT NAME FROM sys.database_principals WHERE NAME =  'COFIDIS2000\GRP_SQL_DEV_TECNICO') BEGIN CREATE USER  [COFIDIS2000\GRP_SQL_DEV_TECNICO] 
   FOR LOGIN [COFIDIS2000\GRP_SQL_DEV_TECNICO] END ELSE ALTER USER  [COFIDIS2000\GRP_SQL_DEV_TECNICO] WITH LOGIN = [COFIDIS2000\GRP_SQL_DEV_TECNICO];
IF DATABASE_PRINCIPAL_ID('COFIDIS2000\GRP_SQL_DEV_TECNICO') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\GRP_SQL_DEV_TECNICO]

ALTER ROLE [db_datareader] ADD MEMBER [COFIDIS2000\GRP_SQL_DEV_TECNICO]
GO
ALTER ROLE [ssis_logreader] ADD MEMBER [COFIDIS2000\GRP_SQL_DEV_TECNICO]
GO
