-- PRD .- HESTIA
--  COFIDIS2000\GRP_SQL_DADOS_MODELOS
--

use master
go
IF EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_DADOS_MODELOS')
     DROP LOGIN [COFIDIS2000\GRP_SQL_DADOS_MODELOS];
GO  

IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_DADOS_MODELOS')
     CREATE LOGIN [COFIDIS2000\GRP_SQL_DADOS_MODELOS] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english];
GO    


EXEC sp_MSforeachdb '
IF ''?'' NOT IN (''master'', ''model'', ''msdb'', ''SSISDB'', ''tempdb''
,''dba_db''
,''RH''
,''DW_AUTO''
) 
BEGIN 
    USE [?]
    PRINT ''?''
	DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_DADOS_MODELOS]

    IF DATABASE_PRINCIPAL_ID(''COFIDIS2000\GRP_SQL_DADOS_MODELOS'') IS NULL
    BEGIN
        PRINT '' Criando o user.''
        CREATE USER [COFIDIS2000\GRP_SQL_DADOS_MODELOS] FROM LOGIN [COFIDIS2000\GRP_SQL_DADOS_MODELOS];
    END /*IF*/
    PRINT '' Adicionar as permissões para o user ...''
	GRANT CONNECT				TO [COFIDIS2000\GRP_SQL_DADOS_MODELOS]
	GRANT SELECT				 TO [COFIDIS2000\GRP_SQL_DADOS_MODELOS] 
	GRANT SHOWPLAN				TO [COFIDIS2000\GRP_SQL_DADOS_MODELOS] 
	GRANT VIEW Definition 		TO [COFIDIS2000\GRP_SQL_DADOS_MODELOS]
	GRANT SHOWPLAN 				TO [COFIDIS2000\GRP_SQL_DADOS_MODELOS]

END /*IF*/
'

Use bd_temp
go
grant execute to [COFIDIS2000\GRP_SQL_DADOS_MODELOS]
go


/*
--Privilégios MSDB
*/
USE [msdb]
GO
DROP SCHEMA IF EXISTS [COFIDIS2000\GRP_SQL_DADOS_MODELOS]
DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_DADOS_MODELOS]
go
IF NOT EXISTS (SELECT NAME FROM sys.database_principals WHERE NAME =  'COFIDIS2000\GRP_SQL_DADOS_MODELOS') BEGIN CREATE USER  [COFIDIS2000\GRP_SQL_DADOS_MODELOS] 
   FOR LOGIN [COFIDIS2000\GRP_SQL_DADOS_MODELOS] END ELSE ALTER USER  [COFIDIS2000\GRP_SQL_DADOS_MODELOS] WITH LOGIN = [COFIDIS2000\GRP_SQL_DADOS_MODELOS];
IF DATABASE_PRINCIPAL_ID('COFIDIS2000\GRP_SQL_DADOS_MODELOS') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\GRP_SQL_DADOS_MODELOS]

exec sp_addrolemember 'SQLAgentOperatorRole', 'COFIDIS2000\GRP_SQL_DEV_SENIOR'
exec sp_addrolemember 'db_ssisoperator', 'COFIDIS2000\GRP_SQL_DADOS_MODELOS'
exec sp_addrolemember 'db_datareader', 'COFIDIS2000\GRP_SQL_DADOS_MODELOS'

/*
--Privilégios SSISDB
*/
USE [SSISDB]
GO
DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_DADOS_MODELOS]
go
IF NOT EXISTS (SELECT NAME FROM sys.database_principals WHERE NAME =  'COFIDIS2000\GRP_SQL_DADOS_MODELOS') BEGIN CREATE USER  [COFIDIS2000\GRP_SQL_DADOS_MODELOS] 
   FOR LOGIN [COFIDIS2000\GRP_SQL_DADOS_MODELOS] END ELSE ALTER USER  [COFIDIS2000\GRP_SQL_DADOS_MODELOS] WITH LOGIN = [COFIDIS2000\GRP_SQL_DADOS_MODELOS];
IF DATABASE_PRINCIPAL_ID('COFIDIS2000\GRP_SQL_DADOS_MODELOS') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\GRP_SQL_DADOS_MODELOS]

ALTER ROLE [db_datareader] ADD MEMBER [COFIDIS2000\GRP_SQL_DADOS_MODELOS]
GO
ALTER ROLE [ssis_admin] ADD MEMBER [COFIDIS2000\GRP_SQL_DADOS_MODELOS]
GO



-- PRD - Arquitectos
--  COFIDIS2000\GRP_SQL_ARQUITECTOS
--

use master
go
IF EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_ARQUITECTOS')
     DROP LOGIN [COFIDIS2000\GRP_SQL_ARQUITECTOS];
GO  

IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_ARQUITECTOS')
     CREATE LOGIN [COFIDIS2000\GRP_SQL_ARQUITECTOS] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english];
GO    


EXEC sp_MSforeachdb '
IF ''?'' NOT IN (''master'', ''model'', ''msdb'', ''SSISDB'', ''tempdb''
,''dba_db''
,''RH''
,''DW_AUTO''


) 
BEGIN 
    USE [?]
    PRINT ''?''
	DROP SCHEMA IF EXISTS [COFIDIS2000\GRP_SQL_ARQUITECTOS]
	DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_ARQUITECTOS]

    IF DATABASE_PRINCIPAL_ID(''COFIDIS2000\GRP_SQL_ARQUITECTOS'') IS NULL
    BEGIN
        PRINT '' Criando o user.''
        CREATE USER [COFIDIS2000\GRP_SQL_ARQUITECTOS] FROM LOGIN [COFIDIS2000\GRP_SQL_ARQUITECTOS];
    END /*IF*/
    PRINT '' Adicionar as permissões para o user ...''
	GRANT CONNECT TO [COFIDIS2000\GRP_SQL_ARQUITECTOS]
	GRANT SELECT                TO [COFIDIS2000\GRP_SQL_ARQUITECTOS] 
	GRANT VIEW Definition 		TO [COFIDIS2000\GRP_SQL_ARQUITECTOS]

END /*IF*/
'


/*
--Privilégios MSDB
*/
USE [msdb]
GO
DROP SCHEMA IF EXISTS [COFIDIS2000\GRP_SQL_ARQUITECTOS]
DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_ARQUITECTOS]
go
IF NOT EXISTS (SELECT NAME FROM sys.database_principals WHERE NAME =  'COFIDIS2000\GRP_SQL_ARQUITECTOS') BEGIN CREATE USER  [COFIDIS2000\GRP_SQL_ARQUITECTOS] 
   FOR LOGIN [COFIDIS2000\GRP_SQL_ARQUITECTOS] END ELSE ALTER USER  [COFIDIS2000\GRP_SQL_ARQUITECTOS] WITH LOGIN = [COFIDIS2000\GRP_SQL_ARQUITECTOS];
IF DATABASE_PRINCIPAL_ID('COFIDIS2000\GRP_SQL_ARQUITECTOS') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\GRP_SQL_ARQUITECTOS]

exec sp_addrolemember 'SQLAgentReaderRole', 'COFIDIS2000\GRP_SQL_ARQUITECTOS'
exec sp_addrolemember 'db_ssisoperator', 'COFIDIS2000\GRP_SQL_ARQUITECTOS'
exec sp_addrolemember 'db_ssisltduser', 'COFIDIS2000\GRP_SQL_ARQUITECTOS'
exec sp_addrolemember 'db_datareader', 'COFIDIS2000\GRP_SQL_ARQUITECTOS'

/*
--Privilégios SSISDB
*/
USE [SSISDB]
GO
DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_ARQUITECTOS]
go
IF NOT EXISTS (SELECT NAME FROM sys.database_principals WHERE NAME =  'COFIDIS2000\GRP_SQL_ARQUITECTOS') BEGIN CREATE USER  [COFIDIS2000\GRP_SQL_ARQUITECTOS] 
   FOR LOGIN [COFIDIS2000\GRP_SQL_ARQUITECTOS] END ELSE ALTER USER  [COFIDIS2000\GRP_SQL_ARQUITECTOS] WITH LOGIN = [COFIDIS2000\GRP_SQL_ARQUITECTOS];
IF DATABASE_PRINCIPAL_ID('COFIDIS2000\GRP_SQL_ARQUITECTOS') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\GRP_SQL_ARQUITECTOS]

ALTER ROLE [db_datareader] ADD MEMBER [COFIDIS2000\GRP_SQL_ARQUITECTOS]
GO
ALTER ROLE [ssis_logreader] ADD MEMBER [COFIDIS2000\GRP_SQL_ARQUITECTOS]
GO



---
-- PRD - SENIORES
--  COFIDIS2000\GRP_SQL_SENIOR_PRD
--

use master
go
IF EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_SENIOR_PRD')
     DROP LOGIN [COFIDIS2000\GRP_SQL_SENIOR_PRD];
GO  

IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_SENIOR_PRD')
     CREATE LOGIN [COFIDIS2000\GRP_SQL_SENIOR_PRD] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english];
GO    


EXEC sp_MSforeachdb '
IF ''?'' IN (
''ReportesBdP'',
''Lusiadas''

) 
BEGIN 
    USE [?]
    PRINT ''?''
	DROP SCHEMA IF EXISTS [COFIDIS2000\GRP_SQL_SENIOR_PRD]
	DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_SENIOR_PRD]

    IF DATABASE_PRINCIPAL_ID(''COFIDIS2000\GRP_SQL_SENIOR_PRD'') IS NULL
    BEGIN
        PRINT '' Criando o user.''
        CREATE USER [COFIDIS2000\GRP_SQL_SENIOR_PRD] FROM LOGIN [COFIDIS2000\GRP_SQL_SENIOR_PRD];
    END /*IF*/
    PRINT '' Adicionar as permissões para o user ...''
	GRANT CONNECT TO [COFIDIS2000\GRP_SQL_SENIOR_PRD]
	GRANT SELECT,insert, update TO [COFIDIS2000\GRP_SQL_SENIOR_PRD] 


END /*IF*/
'


/*
--Privilégios MSDB
*/
USE [msdb]
GO
DROP SCHEMA IF EXISTS [COFIDIS2000\GRP_SQL_SENIOR_PRD]
DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_SENIOR_PRD]
GO
IF NOT EXISTS (SELECT NAME FROM sys.database_principals WHERE NAME =  'COFIDIS2000\GRP_SQL_SENIOR_PRD') BEGIN CREATE USER  [COFIDIS2000\GRP_SQL_SENIOR_PRD] 
   FOR LOGIN [COFIDIS2000\GRP_SQL_SENIOR_PRD] END ELSE ALTER USER  [COFIDIS2000\GRP_SQL_SENIOR_PRD] WITH LOGIN = [COFIDIS2000\GRP_SQL_SENIOR_PRD];
IF DATABASE_PRINCIPAL_ID('COFIDIS2000\GRP_SQL_SENIOR_PRD') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\GRP_SQL_SENIOR_PRD]

exec sp_addrolemember 'SQLAgentOperatorRole', 'COFIDIS2000\GRP_SQL_SENIOR_PRD'
exec sp_addrolemember 'db_ssisoperator', 'COFIDIS2000\GRP_SQL_SENIOR_PRD'
exec sp_addrolemember 'db_ssisltduser', 'COFIDIS2000\GRP_SQL_SENIOR_PRD'
exec sp_addrolemember 'db_datareader', 'COFIDIS2000\GRP_SQL_SENIOR_PRD'

/*
--Privilégios SSISDB
*/
USE [SSISDB]
GO
DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_SENIOR_PRD]
go
IF NOT EXISTS (SELECT NAME FROM sys.database_principals WHERE NAME =  'COFIDIS2000\GRP_SQL_SENIOR_PRD') BEGIN CREATE USER  [COFIDIS2000\GRP_SQL_SENIOR_PRD] 
   FOR LOGIN [COFIDIS2000\GRP_SQL_SENIOR_PRD] END ELSE ALTER USER  [COFIDIS2000\GRP_SQL_SENIOR_PRD] WITH LOGIN = [COFIDIS2000\GRP_SQL_SENIOR_PRD];
IF DATABASE_PRINCIPAL_ID('COFIDIS2000\GRP_SQL_SENIOR_PRD') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\GRP_SQL_SENIOR_PRD]

ALTER ROLE [db_datareader] ADD MEMBER [COFIDIS2000\GRP_SQL_SENIOR_PRD]
GO
ALTER ROLE [ssis_logreader] ADD MEMBER [COFIDIS2000\GRP_SQL_SENIOR_PRD]
GO


--
use master
go
IF EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_COG_FACTORIES')
     DROP LOGIN [COFIDIS2000\GRP_SQL_COG_FACTORIES];
GO  

IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_COG_FACTORIES')
     CREATE LOGIN [COFIDIS2000\GRP_SQL_COG_FACTORIES] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english];
GO    


EXEC sp_MSforeachdb '
IF ''?'' NOT IN (''master'', ''model'', ''msdb'', ''SSISDB'', ''tempdb''

,''AdministracaoSistemas''
,''Almonde''
,''bd_temp''
,''bd_temp_ccm''
,''dba_db''
,''DM_ACM''
,''DM_Actividade''
,''DM_ADEPTRA''
,''DM_CA''
,''DM_CG''
,''DM_CS''
,''DM_DAH''
,''DM_DG''
,''DM_Fraude''
,''DM_GE''
,''DM_IDH''
,''DM_IPCC''
,''DM_ITIL''
,''DM_PAC''
,''DM_ReportServer''
,''DM_RH''
,''DW_AUTO''
,''DM_Risco''
,''DM_VG''
,''DW_AUTO''
,''DW_Historico''
,''InfanteSagres''
,''PerformanceCounters''
,''RH''


) 
BEGIN 
    USE [?]
    PRINT ''?''
	DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_COG_FACTORIES]

    IF DATABASE_PRINCIPAL_ID(''COFIDIS2000\GRP_SQL_COG_FACTORIES'') IS NULL
    BEGIN
        PRINT '' Criando o user.''
        CREATE USER [COFIDIS2000\GRP_SQL_COG_FACTORIES] FROM LOGIN [COFIDIS2000\GRP_SQL_COG_FACTORIES];
    END /*IF*/
    PRINT '' Adicionar as permissões para o user ...''
	GRANT CONNECT TO [COFIDIS2000\GRP_SQL_COG_FACTORIES]
	GRANT SELECT TO [COFIDIS2000\GRP_SQL_COG_FACTORIES] 
	GRANT VIEW Definition 		TO [COFIDIS2000\GRP_SQL_COG_FACTORIES]
	GRANT EXECUTE 				TO [COFIDIS2000\GRP_SQL_COG_FACTORIES]


END /*IF*/
'


/*
--Privilégios MSDB
*/
USE [msdb]
GO
DROP SCHEMA IF EXISTS [COFIDIS2000\GRP_SQL_COG_FACTORIES]
DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_COG_FACTORIES]
go
IF NOT EXISTS (SELECT NAME FROM sys.database_principals WHERE NAME =  'COFIDIS2000\GRP_SQL_COG_FACTORIES') BEGIN CREATE USER  [COFIDIS2000\GRP_SQL_COG_FACTORIES] 
   FOR LOGIN [COFIDIS2000\GRP_SQL_COG_FACTORIES] END ELSE ALTER USER  [COFIDIS2000\GRP_SQL_COG_FACTORIES] WITH LOGIN = [COFIDIS2000\GRP_SQL_COG_FACTORIES];
IF DATABASE_PRINCIPAL_ID('COFIDIS2000\GRP_SQL_COG_FACTORIES') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\GRP_SQL_COG_FACTORIES]

exec sp_addrolemember 'SQLAgentUserRole', 'COFIDIS2000\GRP_SQL_COG_FACTORIES'
exec sp_addrolemember 'db_ssisoperator', 'COFIDIS2000\GRP_SQL_COG_FACTORIES'
exec sp_addrolemember 'db_datareader', 'COFIDIS2000\GRP_SQL_COG_FACTORIES'

/*
--Privilégios SSISDB
*/
USE [SSISDB]
GO
DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_COG_FACTORIES]
go
IF NOT EXISTS (SELECT NAME FROM sys.database_principals WHERE NAME =  'COFIDIS2000\GRP_SQL_COG_FACTORIES') BEGIN CREATE USER  [COFIDIS2000\GRP_SQL_COG_FACTORIES] 
   FOR LOGIN [COFIDIS2000\GRP_SQL_COG_FACTORIES] END ELSE ALTER USER  [COFIDIS2000\GRP_SQL_COG_FACTORIES] WITH LOGIN = [COFIDIS2000\GRP_SQL_COG_FACTORIES];
IF DATABASE_PRINCIPAL_ID('COFIDIS2000\GRP_SQL_COG_FACTORIES') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\GRP_SQL_COG_FACTORIES]

ALTER ROLE [db_datareader] ADD MEMBER [COFIDIS2000\GRP_SQL_COG_FACTORIES]
GO
ALTER ROLE [ssis_admin] ADD MEMBER [COFIDIS2000\GRP_SQL_COG_FACTORIES]
GO

-----

--  SITSQL1
--  COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR
--  HESTIA

use master
go
IF EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR')
     DROP LOGIN [COFIDIS2000\GRP_SQL_COG_FACTORIES];
GO  

IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR')
     CREATE LOGIN [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english];
GO    


EXEC sp_MSforeachdb '
IF ''?'' NOT IN (''master'', ''model'', ''msdb'', ''SSISDB'', ''tempdb''

,''AdministracaoSistemas''
,''Almonde''
,''bd_temp''
,''bd_temp_ccm''
,''dba_db''
,''DM_ACM''
,''DM_Actividade''
,''DM_ADEPTRA''
,''DM_CA''
,''DM_CG''
,''DM_CS''
,''DM_DAH''
,''DM_DG''
,''DM_Fraude''
,''DM_GE''
,''DM_IDH''
,''DM_IPCC''
,''DM_ITIL''
,''DM_PAC''
,''DW_AUTO''
,''DM_ReportServer''
,''DM_RH''
,''DM_Risco''
,''DM_VG''
,''DW_AUTO''
,''DW_Historico''
,''InfanteSagres''
,''PerformanceCounters''
,''RH''




) 
BEGIN 
    USE [?]
    PRINT ''?''
	DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR]

    IF DATABASE_PRINCIPAL_ID(''COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR'') IS NULL
    BEGIN
        PRINT '' Criando o user.''
        CREATE USER [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR] FROM LOGIN [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR];
    END /*IF*/
    PRINT '' Adicionar as permissões para o user ...''
	GRANT CONNECT TO [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR]
	GRANT SELECT TO [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR]  
	GRANT VIEW Definition 		TO [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR]
	GRANT EXECUTE 				TO [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR]


END /*IF*/
'


/*
--Privilégios MSDB
*/
USE [msdb]
GO
DROP SCHEMA IF EXISTS [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR]
DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR]
go
IF NOT EXISTS (SELECT NAME FROM sys.database_principals WHERE NAME =  'COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR') BEGIN CREATE USER  [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR] 
   FOR LOGIN [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR] END ELSE ALTER USER  [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR] WITH LOGIN = [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR];
IF DATABASE_PRINCIPAL_ID('COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR]

exec sp_addrolemember 'SQLAgentUserRole', 'COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR'
exec sp_addrolemember 'db_ssisoperator', 'COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR'
exec sp_addrolemember 'db_datareader', 'COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR'

/*
--Privilégios SSISDB
*/
USE [SSISDB]
GO
DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR]
go
IF NOT EXISTS (SELECT NAME FROM sys.database_principals WHERE NAME =  'COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR') BEGIN CREATE USER  [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR] 
   FOR LOGIN [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR] END ELSE ALTER USER  [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR] WITH LOGIN = [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR];
IF DATABASE_PRINCIPAL_ID('COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR]

ALTER ROLE [db_datareader] ADD MEMBER [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR]
GO
ALTER ROLE [ssis_admin] ADD MEMBER [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR]
GO
--
-- COFIDIS2000\GRP_SQL_BILLING_SENIOR



use master
go
IF EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_BILLING_SENIOR')
     DROP LOGIN [COFIDIS2000\GRP_SQL_BILLING_SENIOR];
GO  

IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_BILLING_SENIOR')
     CREATE LOGIN [COFIDIS2000\GRP_SQL_BILLING_SENIOR] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english];
GO    


EXEC sp_MSforeachdb '
IF ''?'' IN (
''ReportesBdP''



) 
BEGIN 
    USE [?]
    PRINT ''?''
	DROP SCHEMA IF EXISTS [COFIDIS2000\GRP_SQL_BILLING_SENIOR]
	DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_BILLING_SENIOR]

    IF DATABASE_PRINCIPAL_ID(''COFIDIS2000\GRP_SQL_BILLING_SENIOR'') IS NULL
    BEGIN
        PRINT '' Criando o user.''
        CREATE USER [COFIDIS2000\GRP_SQL_BILLING_SENIOR] FROM LOGIN [COFIDIS2000\GRP_SQL_BILLING_SENIOR];
    END /*IF*/
    PRINT '' Adicionar as permissões para o user ...''
	GRANT CONNECT TO [COFIDIS2000\GRP_SQL_BILLING_SENIOR]
	GRANT SELECT , insert, update           TO [COFIDIS2000\GRP_SQL_BILLING_SENIOR] 
	GRANT VIEW Definition 		TO [COFIDIS2000\GRP_SQL_BILLING_SENIOR]
	GRANT EXECUTE 		TO [COFIDIS2000\GRP_SQL_BILLING_SENIOR]

END /*IF*/
'


/*
--Privilégios MSDB
*/
USE [msdb]
GO
DROP SCHEMA IF EXISTS [COFIDIS2000\GRP_SQL_BILLING_SENIOR]
DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_BILLING_SENIOR]
go
IF NOT EXISTS (SELECT NAME FROM sys.database_principals WHERE NAME =  'COFIDIS2000\GRP_SQL_BILLING_SENIOR') BEGIN CREATE USER  [COFIDIS2000\GRP_SQL_BILLING_SENIOR] 
   FOR LOGIN [COFIDIS2000\GRP_SQL_BILLING_SENIOR] END ELSE ALTER USER  [COFIDIS2000\GRP_SQL_BILLING_SENIOR] WITH LOGIN = [COFIDIS2000\GRP_SQL_BILLING_SENIOR];
IF DATABASE_PRINCIPAL_ID('COFIDIS2000\GRP_SQL_BILLING_SENIOR') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\GRP_SQL_BILLING_SENIOR]

exec sp_addrolemember 'SQLAgentReaderRole', 'COFIDIS2000\GRP_SQL_BILLING_SENIOR'
exec sp_addrolemember 'db_ssisoperator', 'COFIDIS2000\GRP_SQL_BILLING_SENIOR'
exec sp_addrolemember 'db_ssisltduser', 'COFIDIS2000\GRP_SQL_BILLING_SENIOR'
exec sp_addrolemember 'db_datareader', 'COFIDIS2000\GRP_SQL_BILLING_SENIOR'

/*
--Privilégios SSISDB
*/
USE [SSISDB]
GO
DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_BILLING_SENIOR]
go
IF NOT EXISTS (SELECT NAME FROM sys.database_principals WHERE NAME =  'COFIDIS2000\GRP_SQL_BILLING_SENIOR') BEGIN CREATE USER  [COFIDIS2000\GRP_SQL_BILLING_SENIOR] 
   FOR LOGIN [COFIDIS2000\GRP_SQL_BILLING_SENIOR] END ELSE ALTER USER  [COFIDIS2000\GRP_SQL_BILLING_SENIOR] WITH LOGIN = [COFIDIS2000\GRP_SQL_BILLING_SENIOR];
IF DATABASE_PRINCIPAL_ID('COFIDIS2000\GRP_SQL_BILLING_SENIOR') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\GRP_SQL_BILLING_SENIOR]

ALTER ROLE [db_datareader] ADD MEMBER [COFIDIS2000\GRP_SQL_BILLING_SENIOR]
GO
ALTER ROLE [ssis_logreader] ADD MEMBER [COFIDIS2000\GRP_SQL_BILLING_SENIOR]
GO


-----------------------------------
/*

Billing Junior apenas ReportsBDP 

*/

-- COFIDIS2000\GRP_SQL_BILLING_JUNIOR



use master
go
IF EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_BILLING_JUNIOR')
     DROP LOGIN [COFIDIS2000\GRP_SQL_BILLING_JUNIOR];
GO  

IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_BILLING_JUNIOR')
     CREATE LOGIN [COFIDIS2000\GRP_SQL_BILLING_JUNIOR] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english];
GO    


EXEC sp_MSforeachdb '
IF ''?'' IN (
''ReportesBdP''



) 
BEGIN 
    USE [?]
    PRINT ''?''
	DROP SCHEMA IF EXISTS [COFIDIS2000\GRP_SQL_BILLING_JUNIOR]
	DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_BILLING_JUNIOR]

    IF DATABASE_PRINCIPAL_ID(''COFIDIS2000\GRP_SQL_BILLING_JUNIOR'') IS NULL
    BEGIN
        PRINT '' Criando o user.''
        CREATE USER [COFIDIS2000\GRP_SQL_BILLING_JUNIOR] FROM LOGIN [COFIDIS2000\GRP_SQL_BILLING_JUNIOR];
    END /*IF*/
    PRINT '' Adicionar as permissões para o user ...''
	GRANT CONNECT TO [COFIDIS2000\GRP_SQL_BILLING_JUNIOR]
	GRANT SELECT , insert, update              TO [COFIDIS2000\GRP_SQL_BILLING_JUNIOR] 
	GRANT VIEW Definition 		TO [COFIDIS2000\GRP_SQL_BILLING_JUNIOR]
	GRANT EXECUTE 		TO [COFIDIS2000\GRP_SQL_BILLING_JUNIOR]

END /*IF*/
'



-- PRD - ARQUITECTURA & ENGENHARIA
--  COFIDIS2000\GRP_SQL_AENG
--  HESTIA

use master
go
IF EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_AENG')
     DROP LOGIN [COFIDIS2000\GRP_SQL_AENG];
GO  

IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_AENG')
     CREATE LOGIN [COFIDIS2000\GRP_SQL_AENG] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english];
GO    


EXEC sp_MSforeachdb '
IF ''?'' IN (''Lusiadas''



) 
BEGIN 
    USE [?]
    PRINT ''?''
	DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_AENG]

    IF DATABASE_PRINCIPAL_ID(''COFIDIS2000\GRP_SQL_AENG'') IS NULL
    BEGIN
        PRINT '' Criando o user.''
        CREATE USER [COFIDIS2000\GRP_SQL_AENG] FROM LOGIN [COFIDIS2000\GRP_SQL_AENG];
    END /*IF*/
    PRINT '' Adicionar as permissões para o user ...''
	GRANT CONNECT TO [COFIDIS2000\GRP_SQL_AENG]
	GRANT SELECT TO [COFIDIS2000\GRP_SQL_AENG]  
	GRANT SHOWPLAN 				TO [COFIDIS2000\GRP_SQL_AENG]

END /*IF*/
'


/*
--Privilégios MSDB
*/
USE [msdb]
GO
DROP SCHEMA IF EXISTS [COFIDIS2000\GRP_SQL_AENG]
DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_AENG]
go
IF NOT EXISTS (SELECT NAME FROM sys.database_principals WHERE NAME =  'COFIDIS2000\GRP_SQL_AENG') BEGIN CREATE USER  [COFIDIS2000\GRP_SQL_AENG] 
   FOR LOGIN [COFIDIS2000\GRP_SQL_AENG] END ELSE ALTER USER  [COFIDIS2000\GRP_SQL_AENG] WITH LOGIN = [COFIDIS2000\GRP_SQL_AENG];
IF DATABASE_PRINCIPAL_ID('COFIDIS2000\GRP_SQL_AENG') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\GRP_SQL_AENG]

exec sp_addrolemember 'SQLAgentUserRole', 'COFIDIS2000\GRP_SQL_AENG'
exec sp_addrolemember 'db_ssisoperator', 'COFIDIS2000\GRP_SQL_AENG'
exec sp_addrolemember 'db_datareader', 'COFIDIS2000\GRP_SQL_AENG'

/*
--Privilégios SSISDB
*/
USE [SSISDB]
GO
DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_AENG]
go
IF NOT EXISTS (SELECT NAME FROM sys.database_principals WHERE NAME =  'COFIDIS2000\GRP_SQL_AENG') BEGIN CREATE USER  [COFIDIS2000\GRP_SQL_AENG] 
   FOR LOGIN [COFIDIS2000\GRP_SQL_AENG] END ELSE ALTER USER  [COFIDIS2000\GRP_SQL_AENG] WITH LOGIN = [COFIDIS2000\GRP_SQL_AENG];
IF DATABASE_PRINCIPAL_ID('COFIDIS2000\GRP_SQL_AENG') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\GRP_SQL_AENG]

ALTER ROLE [db_datareader] ADD MEMBER [COFIDIS2000\GRP_SQL_AENG]
GO

--





--
-- SUPORTE - Suporte aplicacional
--  COFIDIS2000\GRP_SQL_SUPORTE_APP
--

use master
go
IF EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_SUPORTE_APP')
     DROP LOGIN [COFIDIS2000\GRP_SQL_SUPORTE_APP];
GO  

IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_SUPORTE_APP')
     CREATE LOGIN [COFIDIS2000\GRP_SQL_SUPORTE_APP] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english];
GO    


EXEC sp_MSforeachdb '
IF ''?'' NOT IN (''master'', ''model'', ''msdb'', ''SSISDB'', ''tempdb''
,''dba_db''
,''RH''
,''DW_AUTO''

) 
BEGIN 
    USE [?]
    PRINT ''?''
	DROP SCHEMA IF EXISTS [COFIDIS2000\GRP_SQL_SUPORTE_APP]
	DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_SUPORTE_APP]

    IF DATABASE_PRINCIPAL_ID(''COFIDIS2000\GRP_SQL_SUPORTE_APP'') IS NULL
    BEGIN
        PRINT '' Criando o user.''
        CREATE USER [COFIDIS2000\GRP_SQL_SUPORTE_APP] FROM LOGIN [COFIDIS2000\GRP_SQL_SUPORTE_APP];
    END /*IF*/
    PRINT '' Adicionar as permissões para o user ...''
	GRANT CONNECT TO [COFIDIS2000\GRP_SQL_SUPORTE_APP]
	GRANT SELECT,INSERT,UPDATE,DELETE  TO [COFIDIS2000\GRP_SQL_SUPORTE_APP] 
	GRANT VIEW Definition 		TO [COFIDIS2000\GRP_SQL_SUPORTE_APP]
	GRANT execute 		TO [COFIDIS2000\GRP_SQL_SUPORTE_APP]
	GRANT ALTER 		TO [COFIDIS2000\GRP_SQL_SUPORTE_APP]
	GRANT EXECUTE 				TO [COFIDIS2000\GRP_SQL_SUPORTE_APP]

END /*IF*/
'


/*
--Privilégios MSDB
*/
USE [msdb]
GO
DROP SCHEMA IF EXISTS [COFIDIS2000\GRP_SQL_SUPORTE_APP]
DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_SUPORTE_APP]
go
IF NOT EXISTS (SELECT NAME FROM sys.database_principals WHERE NAME =  'COFIDIS2000\GRP_SQL_SUPORTE_APP') BEGIN CREATE USER  [COFIDIS2000\GRP_SQL_SUPORTE_APP] 
   FOR LOGIN [COFIDIS2000\GRP_SQL_SUPORTE_APP] END ELSE ALTER USER  [COFIDIS2000\GRP_SQL_SUPORTE_APP] WITH LOGIN = [COFIDIS2000\GRP_SQL_SUPORTE_APP];
IF DATABASE_PRINCIPAL_ID('COFIDIS2000\GRP_SQL_SUPORTE_APP') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\GRP_SQL_SUPORTE_APP]

exec sp_addrolemember 'SQLAgentOperatorRole', 'COFIDIS2000\GRP_SQL_SUPORTE_APP'
exec sp_addrolemember 'db_ssisoperator', 'COFIDIS2000\GRP_SQL_SUPORTE_APP'
exec sp_addrolemember 'db_ssisltduser', 'COFIDIS2000\GRP_SQL_SUPORTE_APP'
exec sp_addrolemember 'db_datareader', 'COFIDIS2000\GRP_SQL_SUPORTE_APP'

/*
--Privilégios SSISDB
*/
USE [SSISDB]
GO
DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_SUPORTE_APP]
go
IF NOT EXISTS (SELECT NAME FROM sys.database_principals WHERE NAME =  'COFIDIS2000\GRP_SQL_SUPORTE_APP') BEGIN CREATE USER  [COFIDIS2000\GRP_SQL_SUPORTE_APP] 
   FOR LOGIN [COFIDIS2000\GRP_SQL_SUPORTE_APP] END ELSE ALTER USER  [COFIDIS2000\GRP_SQL_SUPORTE_APP] WITH LOGIN = [COFIDIS2000\GRP_SQL_SUPORTE_APP];
IF DATABASE_PRINCIPAL_ID('COFIDIS2000\GRP_SQL_SUPORTE_APP') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\GRP_SQL_SUPORTE_APP]

ALTER ROLE [db_datareader] ADD MEMBER [COFIDIS2000\GRP_SQL_SUPORTE_APP]
GO
ALTER ROLE [ssis_logreader] ADD MEMBER [COFIDIS2000\GRP_SQL_SUPORTE_APP]
GO
