-- PRD .- HESTIA
--  COFIDIS2000\GRP_SQL_DADOS_MODELOS
--

use master
go
IF EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_DADOS_MODELOS')
     DROP LOGIN [COFIDIS2000\GRP_SQL_DADOS_MODELOS];
GO  

IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_DADOS_MODELOS')
     CREATE LOGIN [COFIDIS2000\GRP_SQL_DADOS_MODELOS] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english];
GO    


EXEC sp_MSforeachdb '
IF ''?'' NOT IN (''master'', ''model'', ''msdb'', ''SSISDB'', ''tempdb''
,''dba_db''
,''RH''
) 
BEGIN 
    USE [?]
    PRINT ''?''
	DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_DADOS_MODELOS]

    IF DATABASE_PRINCIPAL_ID(''COFIDIS2000\GRP_SQL_DADOS_MODELOS'') IS NULL
    BEGIN
        PRINT '' Criando o user.''
        CREATE USER [COFIDIS2000\GRP_SQL_DADOS_MODELOS] FROM LOGIN [COFIDIS2000\GRP_SQL_DADOS_MODELOS];
    END /*IF*/
    PRINT '' Adicionar as permissões para o user ...''
	GRANT CONNECT TO [COFIDIS2000\GRP_SQL_DADOS_MODELOS]
	GRANT SELECT				 TO [COFIDIS2000\GRP_SQL_DADOS_MODELOS] 
	GRANT VIEW Definition 		TO [COFIDIS2000\GRP_SQL_DADOS_MODELOS]
	GRANT EXECUTE 				TO [COFIDIS2000\GRP_SQL_DADOS_MODELOS]
	GRANT SHOWPLAN 				TO [COFIDIS2000\GRP_SQL_DADOS_MODELOS]

END /*IF*/
'


/*
--Privilégios MSDB
*/
USE [msdb]
GO
DROP SCHEMA IF EXISTS [COFIDIS2000\GRP_SQL_DADOS_MODELOS]
DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_DADOS_MODELOS]
go
IF NOT EXISTS (SELECT NAME FROM sys.database_principals WHERE NAME =  'COFIDIS2000\GRP_SQL_DADOS_MODELOS') BEGIN CREATE USER  [COFIDIS2000\GRP_SQL_DADOS_MODELOS] 
   FOR LOGIN [COFIDIS2000\GRP_SQL_DADOS_MODELOS] END ELSE ALTER USER  [COFIDIS2000\GRP_SQL_DADOS_MODELOS] WITH LOGIN = [COFIDIS2000\GRP_SQL_DADOS_MODELOS];
IF DATABASE_PRINCIPAL_ID('COFIDIS2000\GRP_SQL_DADOS_MODELOS') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\GRP_SQL_DADOS_MODELOS]

exec sp_addrolemember 'SQLAgentOperatorRole', 'COFIDIS2000\GRP_SQL_DEV_SENIOR'
exec sp_addrolemember 'db_ssisoperator', 'COFIDIS2000\GRP_SQL_DADOS_MODELOS'
exec sp_addrolemember 'db_datareader', 'COFIDIS2000\GRP_SQL_DADOS_MODELOS'

/*
--Privilégios SSISDB
*/
USE [SSISDB]
GO
DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_DADOS_MODELOS]
go
IF NOT EXISTS (SELECT NAME FROM sys.database_principals WHERE NAME =  'COFIDIS2000\GRP_SQL_DADOS_MODELOS') BEGIN CREATE USER  [COFIDIS2000\GRP_SQL_DADOS_MODELOS] 
   FOR LOGIN [COFIDIS2000\GRP_SQL_DADOS_MODELOS] END ELSE ALTER USER  [COFIDIS2000\GRP_SQL_DADOS_MODELOS] WITH LOGIN = [COFIDIS2000\GRP_SQL_DADOS_MODELOS];
IF DATABASE_PRINCIPAL_ID('COFIDIS2000\GRP_SQL_DADOS_MODELOS') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\GRP_SQL_DADOS_MODELOS]

ALTER ROLE [db_datareader] ADD MEMBER [COFIDIS2000\GRP_SQL_DADOS_MODELOS]
GO
ALTER ROLE [ssis_logreader] ADD MEMBER [COFIDIS2000\GRP_SQL_DADOS_MODELOS]
GO

-- UAT - Arquitectos
--  COFIDIS2000\GRP_SQL_ARQUITECTOS
--

use master
go
IF EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_ARQUITECTOS')
     DROP LOGIN [COFIDIS2000\GRP_SQL_ARQUITECTOS];
GO  

IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_ARQUITECTOS')
     CREATE LOGIN [COFIDIS2000\GRP_SQL_ARQUITECTOS] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english];
GO    


EXEC sp_MSforeachdb '
IF ''?'' NOT IN (''master'', ''model'', ''msdb'', ''SSISDB'', ''tempdb''
,''dba_db''
,''RH''


) 
BEGIN 
    USE [?]
    PRINT ''?''
	DROP SCHEMA IF EXISTS [COFIDIS2000\GRP_SQL_ARQUITECTOS]
	DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_ARQUITECTOS]

    IF DATABASE_PRINCIPAL_ID(''COFIDIS2000\GRP_SQL_ARQUITECTOS'') IS NULL
    BEGIN
        PRINT '' Criando o user.''
        CREATE USER [COFIDIS2000\GRP_SQL_ARQUITECTOS] FROM LOGIN [COFIDIS2000\GRP_SQL_ARQUITECTOS];
    END /*IF*/
    PRINT '' Adicionar as permissões para o user ...''
	GRANT CONNECT TO [COFIDIS2000\GRP_SQL_ARQUITECTOS]
	GRANT SELECT                TO [COFIDIS2000\GRP_SQL_ARQUITECTOS] 
	GRANT VIEW Definition 		TO [COFIDIS2000\GRP_SQL_ARQUITECTOS]

END /*IF*/
'


/*
--Privilégios MSDB
*/
USE [msdb]
GO
DROP SCHEMA IF EXISTS [COFIDIS2000\GRP_SQL_ARQUITECTOS]
DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_ARQUITECTOS]
go
IF NOT EXISTS (SELECT NAME FROM sys.database_principals WHERE NAME =  'COFIDIS2000\GRP_SQL_ARQUITECTOS') BEGIN CREATE USER  [COFIDIS2000\GRP_SQL_ARQUITECTOS] 
   FOR LOGIN [COFIDIS2000\GRP_SQL_ARQUITECTOS] END ELSE ALTER USER  [COFIDIS2000\GRP_SQL_ARQUITECTOS] WITH LOGIN = [COFIDIS2000\GRP_SQL_ARQUITECTOS];
IF DATABASE_PRINCIPAL_ID('COFIDIS2000\GRP_SQL_ARQUITECTOS') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\GRP_SQL_ARQUITECTOS]

exec sp_addrolemember 'SQLAgentReaderRole', 'COFIDIS2000\GRP_SQL_ARQUITECTOS'
exec sp_addrolemember 'db_ssisoperator', 'COFIDIS2000\GRP_SQL_ARQUITECTOS'
exec sp_addrolemember 'db_ssisltduser', 'COFIDIS2000\GRP_SQL_ARQUITECTOS'
exec sp_addrolemember 'db_datareader', 'COFIDIS2000\GRP_SQL_ARQUITECTOS'

/*
--Privilégios SSISDB
*/
USE [SSISDB]
GO
DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_ARQUITECTOS]
go
IF NOT EXISTS (SELECT NAME FROM sys.database_principals WHERE NAME =  'COFIDIS2000\GRP_SQL_ARQUITECTOS') BEGIN CREATE USER  [COFIDIS2000\GRP_SQL_ARQUITECTOS] 
   FOR LOGIN [COFIDIS2000\GRP_SQL_ARQUITECTOS] END ELSE ALTER USER  [COFIDIS2000\GRP_SQL_ARQUITECTOS] WITH LOGIN = [COFIDIS2000\GRP_SQL_ARQUITECTOS];
IF DATABASE_PRINCIPAL_ID('COFIDIS2000\GRP_SQL_ARQUITECTOS') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\GRP_SQL_ARQUITECTOS]

ALTER ROLE [db_datareader] ADD MEMBER [COFIDIS2000\GRP_SQL_ARQUITECTOS]
GO
ALTER ROLE [ssis_logreader] ADD MEMBER [COFIDIS2000\GRP_SQL_ARQUITECTOS]
GO



---
-- PRD - SENIORES
--  COFIDIS2000\GRP_SQL_SENIOR_PRD
--

use master
go
IF EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_SENIOR_PRD')
     DROP LOGIN [COFIDIS2000\GRP_SQL_SENIOR_PRD];
GO  

IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_SENIOR_PRD')
     CREATE LOGIN [COFIDIS2000\GRP_SQL_SENIOR_PRD] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english];
GO    


EXEC sp_MSforeachdb '
IF ''?'' NOT IN (''master'', ''model'', ''msdb'', ''SSISDB'', ''tempdb''
,''AdministracaoSistemas''
,''dba_db''
,''RH''
) 
BEGIN 
    USE [?]
    PRINT ''?''
	DROP SCHEMA IF EXISTS [COFIDIS2000\GRP_SQL_SENIOR_PRD]
	DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_SENIOR_PRD]

    IF DATABASE_PRINCIPAL_ID(''COFIDIS2000\GRP_SQL_SENIOR_PRD'') IS NULL
    BEGIN
        PRINT '' Criando o user.''
        CREATE USER [COFIDIS2000\GRP_SQL_SENIOR_PRD] FROM LOGIN [COFIDIS2000\GRP_SQL_SENIOR_PRD];
    END /*IF*/
    PRINT '' Adicionar as permissões para o user ...''
	GRANT CONNECT TO [COFIDIS2000\GRP_SQL_SENIOR_PRD]
	GRANT SELECT TO [COFIDIS2000\GRP_SQL_SENIOR_PRD] 


END /*IF*/
'


/*
--Privilégios MSDB
*/
USE [msdb]
GO
DROP SCHEMA IF EXISTS [COFIDIS2000\GRP_SQL_SENIOR_PRD]
DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_SENIOR_PRD]
go
IF NOT EXISTS (SELECT NAME FROM sys.database_principals WHERE NAME =  'COFIDIS2000\GRP_SQL_SENIOR_PRD') BEGIN CREATE USER  [COFIDIS2000\GRP_SQL_SENIOR_PRD] 
   FOR LOGIN [COFIDIS2000\GRP_SQL_SENIOR_PRD] END ELSE ALTER USER  [COFIDIS2000\GRP_SQL_SENIOR_PRD] WITH LOGIN = [COFIDIS2000\GRP_SQL_SENIOR_PRD];
IF DATABASE_PRINCIPAL_ID('COFIDIS2000\GRP_SQL_SENIOR_PRD') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\GRP_SQL_SENIOR_PRD]

exec sp_addrolemember 'SQLAgentOperatorRole', 'COFIDIS2000\GRP_SQL_SENIOR_PRD'
exec sp_addrolemember 'db_ssisoperator', 'COFIDIS2000\GRP_SQL_SENIOR_PRD'
exec sp_addrolemember 'db_ssisltduser', 'COFIDIS2000\GRP_SQL_SENIOR_PRD'
exec sp_addrolemember 'db_datareader', 'COFIDIS2000\GRP_SQL_SENIOR_PRD'

/*
--Privilégios SSISDB
*/
USE [SSISDB]
GO
DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_SENIOR_PRD]
go
IF NOT EXISTS (SELECT NAME FROM sys.database_principals WHERE NAME =  'COFIDIS2000\GRP_SQL_SENIOR_PRD') BEGIN CREATE USER  [COFIDIS2000\GRP_SQL_SENIOR_PRD] 
   FOR LOGIN [COFIDIS2000\GRP_SQL_SENIOR_PRD] END ELSE ALTER USER  [COFIDIS2000\GRP_SQL_SENIOR_PRD] WITH LOGIN = [COFIDIS2000\GRP_SQL_SENIOR_PRD];
IF DATABASE_PRINCIPAL_ID('COFIDIS2000\GRP_SQL_SENIOR_PRD') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\GRP_SQL_SENIOR_PRD]

ALTER ROLE [db_datareader] ADD MEMBER [COFIDIS2000\GRP_SQL_SENIOR_PRD]
GO
ALTER ROLE [ssis_logreader] ADD MEMBER [COFIDIS2000\GRP_SQL_SENIOR_PRD]
GO



--
-- SUPORTE - Suporte aplicacional
--  COFIDIS2000\GRP_SQL_SUPORTE_APP
--

use master
go
IF EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_SUPORTE_APP')
     DROP LOGIN [COFIDIS2000\GRP_SQL_SUPORTE_APP];
GO  

IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_SUPORTE_APP')
     CREATE LOGIN [COFIDIS2000\GRP_SQL_SUPORTE_APP] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english];
GO    


EXEC sp_MSforeachdb '
IF ''?'' NOT IN (''master'', ''model'', ''msdb'', ''SSISDB'', ''tempdb''
,''dba_db''
,''RH''

) 
BEGIN 
    USE [?]
    PRINT ''?''
	DROP SCHEMA IF EXISTS [COFIDIS2000\GRP_SQL_SUPORTE_APP]
	DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_SUPORTE_APP]

    IF DATABASE_PRINCIPAL_ID(''COFIDIS2000\GRP_SQL_SUPORTE_APP'') IS NULL
    BEGIN
        PRINT '' Criando o user.''
        CREATE USER [COFIDIS2000\GRP_SQL_SUPORTE_APP] FROM LOGIN [COFIDIS2000\GRP_SQL_SUPORTE_APP];
    END /*IF*/
    PRINT '' Adicionar as permissões para o user ...''
	GRANT CONNECT TO [COFIDIS2000\GRP_SQL_SUPORTE_APP]
	GRANT SELECT  TO [COFIDIS2000\GRP_SQL_SUPORTE_APP] 
	GRANT VIEW Definition 		TO [COFIDIS2000\GRP_SQL_SUPORTE_APP]
	GRANT EXECUTE 				TO [COFIDIS2000\GRP_SQL_SUPORTE_APP]

END /*IF*/
'


/*
--Privilégios MSDB
*/
USE [msdb]
GO
DROP SCHEMA IF EXISTS [COFIDIS2000\GRP_SQL_SUPORTE_APP]
DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_SUPORTE_APP]
go
IF NOT EXISTS (SELECT NAME FROM sys.database_principals WHERE NAME =  'COFIDIS2000\GRP_SQL_SUPORTE_APP') BEGIN CREATE USER  [COFIDIS2000\GRP_SQL_SUPORTE_APP] 
   FOR LOGIN [COFIDIS2000\GRP_SQL_SUPORTE_APP] END ELSE ALTER USER  [COFIDIS2000\GRP_SQL_SUPORTE_APP] WITH LOGIN = [COFIDIS2000\GRP_SQL_SUPORTE_APP];
IF DATABASE_PRINCIPAL_ID('COFIDIS2000\GRP_SQL_SUPORTE_APP') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\GRP_SQL_SUPORTE_APP]

exec sp_addrolemember 'SQLAgentOperatorRole', 'COFIDIS2000\GRP_SQL_SUPORTE_APP'
exec sp_addrolemember 'db_ssisoperator', 'COFIDIS2000\GRP_SQL_SUPORTE_APP'
exec sp_addrolemember 'db_ssisltduser', 'COFIDIS2000\GRP_SQL_SUPORTE_APP'
exec sp_addrolemember 'db_datareader', 'COFIDIS2000\GRP_SQL_SUPORTE_APP'

/*
--Privilégios SSISDB
*/
USE [SSISDB]
GO
DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_SUPORTE_APP]
go
IF NOT EXISTS (SELECT NAME FROM sys.database_principals WHERE NAME =  'COFIDIS2000\GRP_SQL_SUPORTE_APP') BEGIN CREATE USER  [COFIDIS2000\GRP_SQL_SUPORTE_APP] 
   FOR LOGIN [COFIDIS2000\GRP_SQL_SUPORTE_APP] END ELSE ALTER USER  [COFIDIS2000\GRP_SQL_SUPORTE_APP] WITH LOGIN = [COFIDIS2000\GRP_SQL_SUPORTE_APP];
IF DATABASE_PRINCIPAL_ID('COFIDIS2000\GRP_SQL_SUPORTE_APP') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\GRP_SQL_SUPORTE_APP]

ALTER ROLE [db_datareader] ADD MEMBER [COFIDIS2000\GRP_SQL_SUPORTE_APP]
GO
ALTER ROLE [ssis_logreader] ADD MEMBER [COFIDIS2000\GRP_SQL_SUPORTE_APP]
GO


