-- Adicionar vários Logins Diomedes
--  COFIDIS2000\GRP_SQL_COG_FACTORIES
--  HESTIA

use master
go
IF EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_COG_FACTORIES')
     DROP LOGIN [COFIDIS2000\GRP_SQL_COG_FACTORIES];
GO  

IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_COG_FACTORIES')
     CREATE LOGIN [COFIDIS2000\GRP_SQL_COG_FACTORIES] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english];
GO    


EXEC sp_MSforeachdb '
IF ''?'' NOT IN (''master'', ''model'', ''msdb'', ''SSISDB'', ''tempdb''

,''db_cofidis_dah_interface''
,''db_cofidis_dah_interface_aux''
,''ExtratoCofidis''
,''FactCofidis''
,''InterfacesDAH''
,''CobrancasDAH''
,''db_cofidis_dah_transactionlog''
,''TControlDAH''
,''ReconciliacaoBancaria''
,''SSISDB''
,''ControlosPermanentes''
,''ContactCenter360''
,''ComunicacaoParceiros''




) 
BEGIN 
    USE [?]
    PRINT ''?''
	DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_COG_FACTORIES]

    IF DATABASE_PRINCIPAL_ID(''COFIDIS2000\GRP_SQL_COG_FACTORIES'') IS NULL
    BEGIN
        PRINT '' Criando o user.''
        CREATE USER [COFIDIS2000\GRP_SQL_COG_FACTORIES] FROM LOGIN [COFIDIS2000\GRP_SQL_COG_FACTORIES];
    END /*IF*/
    PRINT '' Adicionar as permissões para o user ...''
	GRANT CONNECT TO [COFIDIS2000\GRP_SQL_COG_FACTORIES]
	GRANT SELECT,UPDATE, INSERT,delete  TO [COFIDIS2000\GRP_SQL_COG_FACTORIES] 
	GRANT ALTER 				TO [COFIDIS2000\GRP_SQL_COG_FACTORIES]
	GRANT VIEW Definition 		TO [COFIDIS2000\GRP_SQL_COG_FACTORIES]
	GRANT EXECUTE 				TO [COFIDIS2000\GRP_SQL_COG_FACTORIES]
	GRANT SHOWPLAN 				TO [COFIDIS2000\GRP_SQL_COG_FACTORIES]

END /*IF*/
'


/*
--Privilégios MSDB
*/
USE [msdb]
GO
DROP SCHEMA IF EXISTS [COFIDIS2000\GRP_SQL_COG_FACTORIES]
DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_COG_FACTORIES]
go
IF NOT EXISTS (SELECT NAME FROM sys.database_principals WHERE NAME =  'COFIDIS2000\GRP_SQL_COG_FACTORIES') BEGIN CREATE USER  [COFIDIS2000\GRP_SQL_COG_FACTORIES] 
   FOR LOGIN [COFIDIS2000\GRP_SQL_COG_FACTORIES] END ELSE ALTER USER  [COFIDIS2000\GRP_SQL_COG_FACTORIES] WITH LOGIN = [COFIDIS2000\GRP_SQL_COG_FACTORIES];
IF DATABASE_PRINCIPAL_ID('COFIDIS2000\GRP_SQL_COG_FACTORIES') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\GRP_SQL_COG_FACTORIES]

exec sp_addrolemember 'SQLAgentUserRole', 'COFIDIS2000\GRP_SQL_COG_FACTORIES'
exec sp_addrolemember 'db_ssisoperator', 'COFIDIS2000\GRP_SQL_COG_FACTORIES'
exec sp_addrolemember 'db_datareader', 'COFIDIS2000\GRP_SQL_COG_FACTORIES'

/*
--Privilégios SSISDB
*/
USE [SSISDB]
GO
DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_COG_FACTORIES]
go
IF NOT EXISTS (SELECT NAME FROM sys.database_principals WHERE NAME =  'COFIDIS2000\GRP_SQL_COG_FACTORIES') BEGIN CREATE USER  [COFIDIS2000\GRP_SQL_COG_FACTORIES] 
   FOR LOGIN [COFIDIS2000\GRP_SQL_COG_FACTORIES] END ELSE ALTER USER  [COFIDIS2000\GRP_SQL_COG_FACTORIES] WITH LOGIN = [COFIDIS2000\GRP_SQL_COG_FACTORIES];
IF DATABASE_PRINCIPAL_ID('COFIDIS2000\GRP_SQL_COG_FACTORIES') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\GRP_SQL_COG_FACTORIES]

ALTER ROLE [db_datareader] ADD MEMBER [COFIDIS2000\GRP_SQL_COG_FACTORIES]
GO
ALTER ROLE [ssis_admin] ADD MEMBER [COFIDIS2000\GRP_SQL_COG_FACTORIES]
GO

-----

-- DEV
--  COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR
--  HESTIA

use master
go
IF EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR')
     DROP LOGIN [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR];
GO  

IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR')
     CREATE LOGIN [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english];
GO    


EXEC sp_MSforeachdb '
IF ''?'' NOT IN (''master'', ''model'', ''msdb'', ''SSISDB'', ''tempdb''

,''db_cofidis_dah_interface''
,''db_cofidis_dah_interface_aux''
,''ExtratoCofidis''
,''FactCofidis''
,''InterfacesDAH''
,''CobrancasDAH''

,''db_cofidis_dah_transactionlog''
,''TControlDAH''
,''ReconciliacaoBancaria''
,''SSISDB''

,''ControlosPermanentes''
,''ContactCenter360''
,''ComunicacaoParceiros''

) 
BEGIN 
    USE [?]
    PRINT ''?''
	DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR]

    IF DATABASE_PRINCIPAL_ID(''COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR'') IS NULL
    BEGIN
        PRINT '' Criando o user.''
        CREATE USER [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR] FROM LOGIN [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR];
    END /*IF*/
    PRINT '' Adicionar as permissões para o user ...''
	GRANT CONNECT TO [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR]
	GRANT SELECT,UPDATE, INSERT,delete TO [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR]  
	GRANT ALTER 				TO [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR]
	GRANT VIEW Definition 		TO [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR]
	GRANT EXECUTE 				TO [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR]
	GRANT SHOWPLAN 				TO [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR]

END /*IF*/
'


/*
--Privilégios MSDB
*/
USE [msdb]
GO
DROP SCHEMA IF EXISTS [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR]
DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR]
go
IF NOT EXISTS (SELECT NAME FROM sys.database_principals WHERE NAME =  'COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR') BEGIN CREATE USER  [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR] 
   FOR LOGIN [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR] END ELSE ALTER USER  [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR] WITH LOGIN = [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR];
IF DATABASE_PRINCIPAL_ID('COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR]

exec sp_addrolemember 'SQLAgentUserRole', 'COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR'
exec sp_addrolemember 'db_ssisoperator', 'COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR'
exec sp_addrolemember 'db_datareader', 'COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR'

/*
--Privilégios SSISDB
*/
USE [SSISDB]
GO
DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR]
go
IF NOT EXISTS (SELECT NAME FROM sys.database_principals WHERE NAME =  'COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR') BEGIN CREATE USER  [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR] 
   FOR LOGIN [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR] END ELSE ALTER USER  [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR] WITH LOGIN = [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR];
IF DATABASE_PRINCIPAL_ID('COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR]

ALTER ROLE [db_datareader] ADD MEMBER [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR]
GO
ALTER ROLE [ssis_admin] ADD MEMBER [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR]
GO



