-- MINOS - Suporte aplicacional
--  COFIDIS2000\GRP_SQL_SUPORTE_APP
--

use master
go
IF EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_SUPORTE_APP')
     DROP LOGIN [COFIDIS2000\GRP_SQL_SUPORTE_APP];
GO  

IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_SUPORTE_APP')
     CREATE LOGIN [COFIDIS2000\GRP_SQL_SUPORTE_APP] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english];
GO    


EXEC sp_MSforeachdb '
IF ''?'' NOT IN (''master'', ''model'', ''msdb'', ''SSISDB'', ''tempdb''
, ''seguranca'' 

) 
BEGIN 
    USE [?]
    PRINT ''?''
	DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_SUPORTE_APP]

    IF DATABASE_PRINCIPAL_ID(''COFIDIS2000\GRP_SQL_SUPORTE_APP'') IS NULL
    BEGIN
        PRINT '' Criando o user.''
        CREATE USER [COFIDIS2000\GRP_SQL_SUPORTE_APP] FROM LOGIN [COFIDIS2000\GRP_SQL_SUPORTE_APP];
    END /*IF*/
    PRINT '' Adicionar as permissões para o user ...''
	GRANT CONNECT TO [COFIDIS2000\GRP_SQL_SUPORTE_APP]
	GRANT SELECT, UPDATE,INSERT  TO [COFIDIS2000\GRP_SQL_SUPORTE_APP] 
	GRANT VIEW Definition 		TO [COFIDIS2000\GRP_SQL_SUPORTE_APP]
	GRANT EXECUTE 				TO [COFIDIS2000\GRP_SQL_SUPORTE_APP]


END /*IF*/
'


/*
--Privilégios MSDB
*/
USE [msdb]
GO
DROP SCHEMA IF EXISTS [COFIDIS2000\GRP_SQL_SUPORTE_APP]
DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_SUPORTE_APP]
go
IF NOT EXISTS (SELECT NAME FROM sys.database_principals WHERE NAME =  'COFIDIS2000\GRP_SQL_SUPORTE_APP') BEGIN CREATE USER  [COFIDIS2000\GRP_SQL_SUPORTE_APP] 
   FOR LOGIN [COFIDIS2000\GRP_SQL_SUPORTE_APP] END ELSE ALTER USER  [COFIDIS2000\GRP_SQL_SUPORTE_APP] WITH LOGIN = [COFIDIS2000\GRP_SQL_SUPORTE_APP];
IF DATABASE_PRINCIPAL_ID('COFIDIS2000\GRP_SQL_SUPORTE_APP') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\GRP_SQL_SUPORTE_APP]

exec sp_addrolemember 'SQLAgentUserRole', 'COFIDIS2000\GRP_SQL_SUPORTE_APP'
exec sp_addrolemember 'db_ssisoperator', 'COFIDIS2000\GRP_SQL_SUPORTE_APP'
exec sp_addrolemember 'db_datareader', 'COFIDIS2000\GRP_SQL_SUPORTE_APP'


