-- PERSEU

-- PRD - Arquitectos
--  COFIDIS2000\GRP_SQL_ARQUITECTOS
--

use master
go
IF EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_ARQUITECTOS')
     DROP LOGIN [COFIDIS2000\GRP_SQL_ARQUITECTOS];
GO  

IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_ARQUITECTOS')
     CREATE LOGIN [COFIDIS2000\GRP_SQL_ARQUITECTOS] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english];
GO    


EXEC sp_MSforeachdb '
IF ''?'' NOT IN (''master'', ''model'', ''msdb'', ''SSISDB'', ''tempdb''
,''dba_db''

) 
BEGIN 
    USE [?]
    PRINT ''?''
	DROP SCHEMA IF EXISTS [COFIDIS2000\GRP_SQL_ARQUITECTOS]
	DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_ARQUITECTOS]

    IF DATABASE_PRINCIPAL_ID(''COFIDIS2000\GRP_SQL_ARQUITECTOS'') IS NULL
    BEGIN
        PRINT '' Criando o user.''
        CREATE USER [COFIDIS2000\GRP_SQL_ARQUITECTOS] FROM LOGIN [COFIDIS2000\GRP_SQL_ARQUITECTOS];
    END /*IF*/
    PRINT '' Adicionar as permissões para o user ...''
	GRANT CONNECT TO [COFIDIS2000\GRP_SQL_ARQUITECTOS]
	GRANT SELECT TO [COFIDIS2000\GRP_SQL_ARQUITECTOS] 
	GRANT VIEW Definition 		TO [COFIDIS2000\GRP_SQL_ARQUITECTOS]

END /*IF*/
'


/*
--Privilégios MSDB
*/
USE [msdb]
GO
DROP SCHEMA IF EXISTS [COFIDIS2000\GRP_SQL_ARQUITECTOS]
DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_ARQUITECTOS]
go
IF NOT EXISTS (SELECT NAME FROM sys.database_principals WHERE NAME =  'COFIDIS2000\GRP_SQL_ARQUITECTOS') BEGIN CREATE USER  [COFIDIS2000\GRP_SQL_ARQUITECTOS] 
   FOR LOGIN [COFIDIS2000\GRP_SQL_ARQUITECTOS] END ELSE ALTER USER  [COFIDIS2000\GRP_SQL_ARQUITECTOS] WITH LOGIN = [COFIDIS2000\GRP_SQL_ARQUITECTOS];
IF DATABASE_PRINCIPAL_ID('COFIDIS2000\GRP_SQL_ARQUITECTOS') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\GRP_SQL_ARQUITECTOS]

exec sp_addrolemember 'SQLAgentReaderRole', 'COFIDIS2000\GRP_SQL_ARQUITECTOS'
exec sp_addrolemember 'db_ssisoperator', 'COFIDIS2000\GRP_SQL_ARQUITECTOS'
exec sp_addrolemember 'db_ssisltduser', 'COFIDIS2000\GRP_SQL_ARQUITECTOS'
exec sp_addrolemember 'db_datareader', 'COFIDIS2000\GRP_SQL_ARQUITECTOS'

/*
--Privilégios SSISDB
*/
USE [SSISDB]
GO
DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_ARQUITECTOS]
go
IF NOT EXISTS (SELECT NAME FROM sys.database_principals WHERE NAME =  'COFIDIS2000\GRP_SQL_ARQUITECTOS') BEGIN CREATE USER  [COFIDIS2000\GRP_SQL_ARQUITECTOS] 
   FOR LOGIN [COFIDIS2000\GRP_SQL_ARQUITECTOS] END ELSE ALTER USER  [COFIDIS2000\GRP_SQL_ARQUITECTOS] WITH LOGIN = [COFIDIS2000\GRP_SQL_ARQUITECTOS];
IF DATABASE_PRINCIPAL_ID('COFIDIS2000\GRP_SQL_ARQUITECTOS') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\GRP_SQL_ARQUITECTOS]

ALTER ROLE [db_datareader] ADD MEMBER [COFIDIS2000\GRP_SQL_ARQUITECTOS]
GO

ALTER ROLE [ssis_logreader] ADD MEMBER [COFIDIS2000\GRP_SQL_ARQUITECTOS]
GO
ALTER ROLE [ssis_admin] ADD MEMBER [COFIDIS2000\GRP_SQL_ARQUITECTOS]
GO


---
-- PRD - SENIORES
--  COFIDIS2000\GRP_SQL_SENIOR_PRD
--

use master
go
IF EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_SENIOR_PRD')
     DROP LOGIN [COFIDIS2000\GRP_SQL_SENIOR_PRD];
GO  

IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_SENIOR_PRD')
     CREATE LOGIN [COFIDIS2000\GRP_SQL_SENIOR_PRD] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english];
GO    


EXEC sp_MSforeachdb '
IF ''?'' NOT IN (''master'', ''model'', ''msdb'', ''SSISDB'', ''tempdb''
,''dba_db''



) 
BEGIN 
    USE [?]
    PRINT ''?''
	DROP SCHEMA IF EXISTS [COFIDIS2000\GRP_SQL_SENIOR_PRD]
	DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_SENIOR_PRD]

    IF DATABASE_PRINCIPAL_ID(''COFIDIS2000\GRP_SQL_SENIOR_PRD'') IS NULL
    BEGIN
        PRINT '' Criando o user.''
        CREATE USER [COFIDIS2000\GRP_SQL_SENIOR_PRD] FROM LOGIN [COFIDIS2000\GRP_SQL_SENIOR_PRD];
    END /*IF*/
    PRINT '' Adicionar as permissões para o user ...''
	GRANT CONNECT TO [COFIDIS2000\GRP_SQL_SENIOR_PRD]
	GRANT SELECT TO [COFIDIS2000\GRP_SQL_SENIOR_PRD] 

END /*IF*/
'


/*
--Privilégios MSDB
*/
USE [msdb]
GO
DROP SCHEMA IF EXISTS [COFIDIS2000\GRP_SQL_SENIOR_PRD]
DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_SENIOR_PRD]
go
IF NOT EXISTS (SELECT NAME FROM sys.database_principals WHERE NAME =  'COFIDIS2000\GRP_SQL_SENIOR_PRD') BEGIN CREATE USER  [COFIDIS2000\GRP_SQL_SENIOR_PRD] 
   FOR LOGIN [COFIDIS2000\GRP_SQL_SENIOR_PRD] END ELSE ALTER USER  [COFIDIS2000\GRP_SQL_SENIOR_PRD] WITH LOGIN = [COFIDIS2000\GRP_SQL_SENIOR_PRD];
IF DATABASE_PRINCIPAL_ID('COFIDIS2000\GRP_SQL_SENIOR_PRD') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\GRP_SQL_SENIOR_PRD]

exec sp_addrolemember 'SQLAgentReaderRole', 'COFIDIS2000\GRP_SQL_SENIOR_PRD'
exec sp_addrolemember 'db_ssisoperator', 'COFIDIS2000\GRP_SQL_SENIOR_PRD'
exec sp_addrolemember 'db_ssisltduser', 'COFIDIS2000\GRP_SQL_SENIOR_PRD'
exec sp_addrolemember 'db_datareader', 'COFIDIS2000\GRP_SQL_SENIOR_PRD'

/*
--Privilégios SSISDB
*/
USE [SSISDB]
GO
DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_SENIOR_PRD]
go
IF NOT EXISTS (SELECT NAME FROM sys.database_principals WHERE NAME =  'COFIDIS2000\GRP_SQL_SENIOR_PRD') BEGIN CREATE USER  [COFIDIS2000\GRP_SQL_SENIOR_PRD] 
   FOR LOGIN [COFIDIS2000\GRP_SQL_SENIOR_PRD] END ELSE ALTER USER  [COFIDIS2000\GRP_SQL_SENIOR_PRD] WITH LOGIN = [COFIDIS2000\GRP_SQL_SENIOR_PRD];
IF DATABASE_PRINCIPAL_ID('COFIDIS2000\GRP_SQL_SENIOR_PRD') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\GRP_SQL_SENIOR_PRD]

ALTER ROLE [db_datareader] ADD MEMBER [COFIDIS2000\GRP_SQL_SENIOR_PRD]
GO
ALTER ROLE [ssis_logreader] ADD MEMBER [COFIDIS2000\GRP_SQL_SENIOR_PRD]
GO

ALTER ROLE [ssis_admin] ADD MEMBER [COFIDIS2000\GRP_SQL_SENIOR_PRD]
GO



--
-- SUPORTE - Suporte aplicacional
--  COFIDIS2000\GRP_SQL_SUPORTE_APP
--

use master
go
IF EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_SUPORTE_APP')
     DROP LOGIN [COFIDIS2000\GRP_SQL_SUPORTE_APP];
GO  

IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_SUPORTE_APP')
     CREATE LOGIN [COFIDIS2000\GRP_SQL_SUPORTE_APP] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english];
GO    


EXEC sp_MSforeachdb '
IF ''?'' NOT IN (''master'', ''model'', ''msdb'', ''SSISDB'', ''tempdb''
,''AdministracaoSistemas''
,''dba_db''


) 
BEGIN 
    USE [?]
    PRINT ''?''
	DROP SCHEMA IF EXISTS [COFIDIS2000\GRP_SQL_SUPORTE_APP]
	DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_SUPORTE_APP]

    IF DATABASE_PRINCIPAL_ID(''COFIDIS2000\GRP_SQL_SUPORTE_APP'') IS NULL
    BEGIN
        PRINT '' Criando o user.''
        CREATE USER [COFIDIS2000\GRP_SQL_SUPORTE_APP] FROM LOGIN [COFIDIS2000\GRP_SQL_SUPORTE_APP];
    END /*IF*/
    PRINT '' Adicionar as permissões para o user ...''
	GRANT CONNECT TO [COFIDIS2000\GRP_SQL_SUPORTE_APP]
	GRANT SELECT, UPDATE,INSERT  TO [COFIDIS2000\GRP_SQL_SUPORTE_APP] 
	GRANT VIEW Definition 		TO [COFIDIS2000\GRP_SQL_SUPORTE_APP]
	GRANT EXECUTE 				TO [COFIDIS2000\GRP_SQL_SUPORTE_APP]

END /*IF*/
'


/*
--Privilégios MSDB
*/
USE [msdb]
GO
DROP SCHEMA IF EXISTS [COFIDIS2000\GRP_SQL_SUPORTE_APP]
DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_SUPORTE_APP]
go
IF NOT EXISTS (SELECT NAME FROM sys.database_principals WHERE NAME =  'COFIDIS2000\GRP_SQL_SUPORTE_APP') BEGIN CREATE USER  [COFIDIS2000\GRP_SQL_SUPORTE_APP] 
   FOR LOGIN [COFIDIS2000\GRP_SQL_SUPORTE_APP] END ELSE ALTER USER  [COFIDIS2000\GRP_SQL_SUPORTE_APP] WITH LOGIN = [COFIDIS2000\GRP_SQL_SUPORTE_APP];
IF DATABASE_PRINCIPAL_ID('COFIDIS2000\GRP_SQL_SUPORTE_APP') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\GRP_SQL_SUPORTE_APP]

exec sp_addrolemember 'SQLAgentOperatorRole', 'COFIDIS2000\GRP_SQL_SUPORTE_APP'
exec sp_addrolemember 'db_ssisoperator', 'COFIDIS2000\GRP_SQL_SUPORTE_APP'
exec sp_addrolemember 'db_ssisltduser', 'COFIDIS2000\GRP_SQL_SUPORTE_APP'
exec sp_addrolemember 'db_datareader', 'COFIDIS2000\GRP_SQL_SUPORTE_APP'

/*
--Privilégios SSISDB
*/
USE [SSISDB]
GO
DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_SUPORTE_APP]
go
IF NOT EXISTS (SELECT NAME FROM sys.database_principals WHERE NAME =  'COFIDIS2000\GRP_SQL_SUPORTE_APP') BEGIN CREATE USER  [COFIDIS2000\GRP_SQL_SUPORTE_APP] 
   FOR LOGIN [COFIDIS2000\GRP_SQL_SUPORTE_APP] END ELSE ALTER USER  [COFIDIS2000\GRP_SQL_SUPORTE_APP] WITH LOGIN = [COFIDIS2000\GRP_SQL_SUPORTE_APP];
IF DATABASE_PRINCIPAL_ID('COFIDIS2000\GRP_SQL_SUPORTE_APP') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\GRP_SQL_SUPORTE_APP]

ALTER ROLE [db_datareader] ADD MEMBER [COFIDIS2000\GRP_SQL_SUPORTE_APP]
GO
ALTER ROLE [ssis_logreader] ADD MEMBER [COFIDIS2000\GRP_SQL_SUPORTE_APP]
GO
--
-- Excepções:
USE db_cofidis_dah
go
GRANT delete on dbo.dossierbloqueio to [COFIDIS2000\GRP_SQL_SUPORTE_APP]
GO
USE db_cofidis_dah_interface_aux
go
grant delete on dbo.dossierbloqueio to [COFIDIS2000\GRP_SQL_SUPORTE_APP]
GO

USE db_cofidis_dah_interface_aux
go
grant delete on [dbo].[tmp_PagamentoExcluir] to [COFIDIS2000\GRP_SQL_SUPORTE_APP]
go

USE master
go 
GRANT ADMINISTER BULK OPERATIONS to [COFIDIS2000\GRP_SQL_SUPORTE_APP]




-- Factories -- SENIORES

--
-- Factori4es

--
-- PRD - Factori4es
--  COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR
--

use master
go
IF EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR')
     DROP LOGIN [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR];
GO  

IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR')
     CREATE LOGIN [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english];
GO    


EXEC sp_MSforeachdb '
IF ''?'' NOT IN (''master'', ''model'', ''msdb'', ''SSISDB'', ''tempdb''
,''AdministracaoSistemas''
,''ComunicacaoParceiros''
,''ControlosPermanentes''
,''db_cofidis_alteracoes''
,''db_cofidis_dah_interface''
,''db_cofidis_dah_interface_aux''
,''db_cofidis_dah_transactionlog''
,''dba_db''
,''ExtratoCofidis''
,''FactCofidis''
,''Interfacesdah''
,''ReconciliacaoBancaria''

) 
BEGIN 
    USE [?]
    PRINT ''?''
	DROP SCHEMA IF EXISTS [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR]
	DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR]

    IF DATABASE_PRINCIPAL_ID(''COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR'') IS NULL
    BEGIN
        PRINT '' Criando o user.''
        CREATE USER [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR] FROM LOGIN [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR];
    END /*IF*/
    PRINT '' Adicionar as permissões para o user ...''
	GRANT CONNECT TO [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR]
	GRANT SELECT				 TO [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR] 

END /*IF*/
'


/*
--Privilégios MSDB
*/
USE [msdb]
GO
DROP SCHEMA IF EXISTS [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR]
DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR]
go
IF NOT EXISTS (SELECT NAME FROM sys.database_principals WHERE NAME =  'COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR') BEGIN CREATE USER  [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR] 
   FOR LOGIN [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR] END ELSE ALTER USER  [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR] WITH LOGIN = [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR];
IF DATABASE_PRINCIPAL_ID('COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR]

exec sp_addrolemember 'db_ssisltduser', 'COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR'
exec sp_addrolemember 'db_datareader', 'COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR'

/*
--Privilégios SSISDB
*/
USE [SSISDB]
GO
DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR]
go
IF NOT EXISTS (SELECT NAME FROM sys.database_principals WHERE NAME =  'COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR') BEGIN CREATE USER  [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR] 
   FOR LOGIN [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR] END ELSE ALTER USER  [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR] WITH LOGIN = [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR];
IF DATABASE_PRINCIPAL_ID('COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR]

ALTER ROLE [db_datareader] ADD MEMBER [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR]
GO
ALTER ROLE [ssis_logreader] ADD MEMBER [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR]
GO


-- BILLING

--
-- PRD - 
--  COFIDIS2000\GRP_SQL_BILLING_SENIOR
--

use master
go
IF EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_BILLING_SENIOR')
     DROP LOGIN [COFIDIS2000\GRP_SQL_BILLING_SENIOR];
GO  

IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_BILLING_SENIOR')
     CREATE LOGIN [COFIDIS2000\GRP_SQL_BILLING_SENIOR] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english];
GO    


EXEC sp_MSforeachdb '
IF ''?'' NOT IN (''master'', ''model'', ''msdb'', ''SSISDB'', ''tempdb''
,''dba_db''


) 
BEGIN 
    USE [?]
    PRINT ''?''
	DROP SCHEMA IF EXISTS [COFIDIS2000\GRP_SQL_BILLING_SENIOR]
	DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_BILLING_SENIOR]

    IF DATABASE_PRINCIPAL_ID(''COFIDIS2000\GRP_SQL_BILLING_SENIOR'') IS NULL
    BEGIN
        PRINT '' Criando o user.''
        CREATE USER [COFIDIS2000\GRP_SQL_BILLING_SENIOR] FROM LOGIN [COFIDIS2000\GRP_SQL_BILLING_SENIOR];
    END /*IF*/
    PRINT '' Adicionar as permissões para o user ...''
	GRANT CONNECT 				 TO [COFIDIS2000\GRP_SQL_BILLING_SENIOR]
	GRANT SELECT, UPDATE, INSERT TO [COFIDIS2000\GRP_SQL_BILLING_SENIOR] 
	GRANT EXECUTE 				 TO [COFIDIS2000\GRP_SQL_BILLING_SENIOR]
	GRANT VIEW Definition 	     TO [COFIDIS2000\GRP_SQL_BILLING_SENIOR]

END /*IF*/
'
-- Excepções para este grupo
-- DELETE
grant delete on Temp_DocumentoFCT  TO [COFIDIS2000\GRP_SQL_BILLING_SENIOR]
grant delete on Temp_Entidade TO [COFIDIS2000\GRP_SQL_BILLING_SENIOR]
grant delete on Temp_EventoDocumento TO [COFIDIS2000\GRP_SQL_BILLING_SENIOR]
grant delete on Temp_EventoMovimento TO [COFIDIS2000\GRP_SQL_BILLING_SENIOR]
grant delete on Temp_Imposto TO [COFIDIS2000\GRP_SQL_BILLING_SENIOR]
grant delete on Temp_ImpostoPeriodo TO [COFIDIS2000\GRP_SQL_BILLING_SENIOR]
grant delete on Temp_Matricula TO [COFIDIS2000\GRP_SQL_BILLING_SENIOR]
grant delete on Temp_Morada TO [COFIDIS2000\GRP_SQL_BILLING_SENIOR]
grant delete on Temp_MovParceiro TO [COFIDIS2000\GRP_SQL_BILLING_SENIOR]
grant delete on Temp_Parceiro TO [COFIDIS2000\GRP_SQL_BILLING_SENIOR]
grant delete on Temp_ProcessoSituacoesAnomalas TO [COFIDIS2000\GRP_SQL_BILLING_SENIOR]
grant delete on Temp_TabelaGeral TO [COFIDIS2000\GRP_SQL_BILLING_SENIOR]
grant delete on Temp_Titular TO [COFIDIS2000\GRP_SQL_BILLING_SENIOR]




/*
--Privilégios MSDB
*/
USE [msdb]
GO
DROP SCHEMA IF EXISTS [COFIDIS2000\GRP_SQL_BILLING_SENIOR]
DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_BILLING_SENIOR]
go
IF NOT EXISTS (SELECT NAME FROM sys.database_principals WHERE NAME =  'COFIDIS2000\GRP_SQL_BILLING_SENIOR') BEGIN CREATE USER  [COFIDIS2000\GRP_SQL_BILLING_SENIOR] 
   FOR LOGIN [COFIDIS2000\GRP_SQL_BILLING_SENIOR] END ELSE ALTER USER  [COFIDIS2000\GRP_SQL_BILLING_SENIOR] WITH LOGIN = [COFIDIS2000\GRP_SQL_BILLING_SENIOR];
IF DATABASE_PRINCIPAL_ID('COFIDIS2000\GRP_SQL_BILLING_SENIOR') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\GRP_SQL_BILLING_SENIOR]

exec sp_addrolemember 'SQLAgentOperatorRole', 'COFIDIS2000\GRP_SQL_BILLING_SENIOR'
exec sp_addrolemember 'db_ssisoperator', 'COFIDIS2000\GRP_SQL_BILLING_SENIOR'
exec sp_addrolemember 'db_ssisltduser', 'COFIDIS2000\GRP_SQL_BILLING_SENIOR'
exec sp_addrolemember 'db_datareader', 'COFIDIS2000\GRP_SQL_BILLING_SENIOR'

USE [SSISDB]
GO
DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_BILLING_SENIOR]
go
IF NOT EXISTS (SELECT NAME FROM sys.database_principals WHERE NAME =  'COFIDIS2000\GRP_SQL_BILLING_SENIOR') BEGIN CREATE USER  [COFIDIS2000\GRP_SQL_BILLING_SENIOR] 
   FOR LOGIN [COFIDIS2000\GRP_SQL_BILLING_SENIOR] END ELSE ALTER USER  [COFIDIS2000\GRP_SQL_BILLING_SENIOR] WITH LOGIN = [COFIDIS2000\GRP_SQL_BILLING_SENIOR];
IF DATABASE_PRINCIPAL_ID('COFIDIS2000\GRP_SQL_BILLING_SENIOR') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\GRP_SQL_BILLING_SENIOR]

ALTER ROLE [db_datareader] ADD MEMBER [COFIDIS2000\GRP_SQL_BILLING_SENIOR]
GO
ALTER ROLE [ssis_logreader] ADD MEMBER [COFIDIS2000\GRP_SQL_BILLING_SENIOR]
GO



-- BILLING JUNIOR

--
-- PRD - 
--  COFIDIS2000\GRP_SQL_BILLING_JUNIOR
--

use master
go
IF EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_BILLING_JUNIOR')
     DROP LOGIN [COFIDIS2000\GRP_SQL_BILLING_JUNIOR];
GO  

IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_BILLING_JUNIOR')
     CREATE LOGIN [COFIDIS2000\GRP_SQL_BILLING_JUNIOR] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english];
GO    


EXEC sp_MSforeachdb '
IF ''?'' NOT IN (''master'', ''model'', ''msdb'', ''SSISDB'', ''tempdb''
,''dba_db''


) 
BEGIN 
    USE [?]
    PRINT ''?''
	DROP SCHEMA IF EXISTS [COFIDIS2000\GRP_SQL_BILLING_JUNIOR]
	DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_BILLING_JUNIOR]

    IF DATABASE_PRINCIPAL_ID(''COFIDIS2000\GRP_SQL_BILLING_JUNIOR'') IS NULL
    BEGIN
        PRINT '' Criando o user.''
        CREATE USER [COFIDIS2000\GRP_SQL_BILLING_JUNIOR] FROM LOGIN [COFIDIS2000\GRP_SQL_BILLING_JUNIOR];
    END /*IF*/
    PRINT '' Adicionar as permissões para o user ...''
	GRANT CONNECT 				 TO [COFIDIS2000\GRP_SQL_BILLING_JUNIOR]
	GRANT SELECT				 TO [COFIDIS2000\GRP_SQL_BILLING_JUNIOR] 


END /*IF*/
'


/*
--Privilégios MSDB
*/
USE [msdb]
GO
DROP SCHEMA IF EXISTS [COFIDIS2000\GRP_SQL_BILLING_JUNIOR]
DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_BILLING_JUNIOR]
go
IF NOT EXISTS (SELECT NAME FROM sys.database_principals WHERE NAME =  'COFIDIS2000\GRP_SQL_BILLING_JUNIOR') BEGIN CREATE USER  [COFIDIS2000\GRP_SQL_BILLING_JUNIOR] 
   FOR LOGIN [COFIDIS2000\GRP_SQL_BILLING_JUNIOR] END ELSE ALTER USER  [COFIDIS2000\GRP_SQL_BILLING_JUNIOR] WITH LOGIN = [COFIDIS2000\GRP_SQL_BILLING_JUNIOR];
IF DATABASE_PRINCIPAL_ID('COFIDIS2000\GRP_SQL_BILLING_JUNIOR') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\GRP_SQL_BILLING_JUNIOR]

exec sp_addrolemember 'SQLAgentOperatorRole', 'COFIDIS2000\GRP_SQL_BILLING_JUNIOR'
exec sp_addrolemember 'db_ssisoperator', 'COFIDIS2000\GRP_SQL_BILLING_JUNIOR'
exec sp_addrolemember 'db_ssisltduser', 'COFIDIS2000\GRP_SQL_BILLING_JUNIOR'
exec sp_addrolemember 'db_datareader', 'COFIDIS2000\GRP_SQL_BILLING_JUNIOR'

USE [SSISDB]
GO
DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_BILLING_JUNIOR]
go
IF NOT EXISTS (SELECT NAME FROM sys.database_principals WHERE NAME =  'COFIDIS2000\GRP_SQL_BILLING_JUNIOR') BEGIN CREATE USER  [COFIDIS2000\GRP_SQL_BILLING_JUNIOR] 
   FOR LOGIN [COFIDIS2000\GRP_SQL_BILLING_JUNIOR] END ELSE ALTER USER  [COFIDIS2000\GRP_SQL_BILLING_JUNIOR] WITH LOGIN = [COFIDIS2000\GRP_SQL_BILLING_JUNIOR];
IF DATABASE_PRINCIPAL_ID('COFIDIS2000\GRP_SQL_BILLING_JUNIOR') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\GRP_SQL_BILLING_JUNIOR]

ALTER ROLE [db_datareader] ADD MEMBER [COFIDIS2000\GRP_SQL_BILLING_JUNIOR]
GO
ALTER ROLE [ssis_admin] ADD MEMBER [COFIDIS2000\GRP_SQL_BILLING_JUNIOR]
GO

/* IDH
use master
go
IF EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_BILLING_JUNIOR')
     DROP LOGIN [COFIDIS2000\GRP_SQL_BILLING_JUNIOR];
GO  

IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_BILLING_JUNIOR')
     CREATE LOGIN [COFIDIS2000\GRP_SQL_BILLING_JUNIOR] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english];
GO    
use TCONTROLDAH

GRANT CONNECT 				 TO [COFIDIS2000\GRP_SQL_BILLING_JUNIOR]
GRANT SELECT				 TO [COFIDIS2000\GRP_SQL_BILLING_JUNIOR] 
go

*/

-- PRD- ARTEMIS
--  COFIDIS2000\GRP_SQL_EXT_PRD  (Moisés)
--  

use master
go
IF EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_EXT_PRD')
     DROP LOGIN [COFIDIS2000\GRP_SQL_EXT_PRD];
GO  

IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_EXT_PRD')
     CREATE LOGIN [COFIDIS2000\GRP_SQL_EXT_PRD] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english];
GO    


EXEC sp_MSforeachdb '
IF ''?'' IN (''DB_Cofidis_DAH'', ''PartnerBorderaux'') 
BEGIN 
    USE [?]
    PRINT ''?''
	DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_EXT_PRD]

    IF DATABASE_PRINCIPAL_ID(''COFIDIS2000\GRP_SQL_EXT_PRD'') IS NULL
    BEGIN
        PRINT '' Criando o user.''
        CREATE USER [COFIDIS2000\GRP_SQL_EXT_PRD] FROM LOGIN [COFIDIS2000\GRP_SQL_EXT_PRD];
    END /*IF*/
    PRINT '' Adicionar as permissões para o user ...''
    grant select on PERSEU.DB_Cofidis_DAH.dbo.Dossier TO [COFIDIS2000\GRP_SQL_EXT_PRD]
	GRANT SHOWPLAN 				TO [COFIDIS2000\GRP_SQL_EXT_PRD]

END /*IF*/
'

-----

