-- PRD- ARTEMIS
--  COFIDIS2000\GRP_SQL_SUPORTE_APP
--  

use master
go
--IF EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_SUPORTE_APP')
--     DROP LOGIN [COFIDIS2000\GRP_SQL_SUPORTE_APP];
--GO  

--IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = 'COFIDIS2000\GRP_SQL_SUPORTE_APP')
--     CREATE LOGIN [COFIDIS2000\GRP_SQL_SUPORTE_APP] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english];
--GO    


EXEC sp_MSforeachdb '
IF ''?'' IN (''RskDecisao'') 
BEGIN 
    USE [?]
    PRINT ''?''
	DROP USER IF EXISTS [COFIDIS2000\GRP_SQL_SUPORTE_APP]

    IF DATABASE_PRINCIPAL_ID(''COFIDIS2000\GRP_SQL_SUPORTE_APP'') IS NULL
    BEGIN
        PRINT '' Criando o user.''
        CREATE USER [COFIDIS2000\GRP_SQL_SUPORTE_APP] FROM LOGIN [COFIDIS2000\GRP_SQL_SUPORTE_APP];
    END /*IF*/
    PRINT '' Adicionar as permissões para o user ...''
	GRANT CONNECT TO [COFIDIS2000\GRP_SQL_SUPORTE_APP]
	GRANT SELECT,update,insert,execute  TO [COFIDIS2000\GRP_SQL_SUPORTE_APP] 
	GRANT VIEW Definition 		TO [COFIDIS2000\GRP_SQL_SUPORTE_APP]
	GRANT SHOWPLAN 				TO [COFIDIS2000\GRP_SQL_SUPORTE_APP]

END /*IF*/
'


-----

