
-- Login: COFIDIS2000\GRP_SQL_AENG
IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = N'COFIDIS2000\GRP_SQL_AENG')
                  BEGIN
CREATE LOGIN [COFIDIS2000\GRP_SQL_AENG] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
END
 
-- Login: COFIDIS2000\GRP_SQL_ARQUITECTOS
IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = N'COFIDIS2000\GRP_SQL_ARQUITECTOS')
                  BEGIN
CREATE LOGIN [COFIDIS2000\GRP_SQL_ARQUITECTOS] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
END
 
-- Login: COFIDIS2000\GRP_SQL_BILLING_JUNIOR
IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = N'COFIDIS2000\GRP_SQL_BILLING_JUNIOR')
                  BEGIN
CREATE LOGIN [COFIDIS2000\GRP_SQL_BILLING_JUNIOR] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
END
 
-- Login: COFIDIS2000\GRP_SQL_BILLING_SENIOR
IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = N'COFIDIS2000\GRP_SQL_BILLING_SENIOR')
                  BEGIN
CREATE LOGIN [COFIDIS2000\GRP_SQL_BILLING_SENIOR] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
END
 
-- Login: COFIDIS2000\Grp_SQL_Billing_Suporte
IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = N'COFIDIS2000\Grp_SQL_Billing_Suporte')
                  BEGIN
CREATE LOGIN [COFIDIS2000\Grp_SQL_Billing_Suporte] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
END
 
-- Login: COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR
IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = N'COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR')
                  BEGIN
CREATE LOGIN [COFIDIS2000\GRP_SQL_COG_FACTORIES_SENIOR] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
END
 
-- Login: COFIDIS2000\GRP_SQL_DELIVERY_PREV
IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = N'COFIDIS2000\GRP_SQL_DELIVERY_PREV')
                  BEGIN
CREATE LOGIN [COFIDIS2000\GRP_SQL_DELIVERY_PREV] FROM WINDOWS WITH DEFAULT_DATABASE = [master]

          EXEC master.dbo.sp_addsrvrolemember @loginame='COFIDIS2000\GRP_SQL_DELIVERY_PREV', @rolename='processadmin'
END
 
-- Login: COFIDIS2000\GRP_SQL_KPIS
IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = N'COFIDIS2000\GRP_SQL_KPIS')
                  BEGIN
CREATE LOGIN [COFIDIS2000\GRP_SQL_KPIS] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
END
 
-- Login: COFIDIS2000\GRP_SQL_SENIOR_PRD
IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = N'COFIDIS2000\GRP_SQL_SENIOR_PRD')
                  BEGIN
CREATE LOGIN [COFIDIS2000\GRP_SQL_SENIOR_PRD] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
END
 
-- Login: COFIDIS2000\GRP_SQL_SUPORTE_APP
IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = N'COFIDIS2000\GRP_SQL_SUPORTE_APP')
                  BEGIN
CREATE LOGIN [COFIDIS2000\GRP_SQL_SUPORTE_APP] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
END