exec ('USE master
GO



USE cofcc_awdb
go


IF DATABASE_PRINCIPAL_ID(''grafana_readonly'') IS NOT NULL DROP USER [grafana_readonly];
IF DATABASE_PRINCIPAL_ID(''lnk_aw12012'') IS NOT NULL DROP USER [lnk_aw12012];
IF DATABASE_PRINCIPAL_ID(''COFIDIS2000\PIRS_SVC_UNN'') IS NOT NULL DROP USER [COFIDIS2000\PIRS_SVC_UNN];
IF DATABASE_PRINCIPAL_ID(''COFIDIS2000\SPServices_SRV_PROD'') IS NOT NULL DROP USER [COFIDIS2000\SPServices_SRV_PROD];
IF DATABASE_PRINCIPAL_ID(''COFIDIS2000\AGTSVC'') IS NOT NULL DROP USER [COFIDIS2000\AGTSVC];
IF DATABASE_PRINCIPAL_ID(''COFIDIS2000\grpSQLArquitetosSDA'') IS NOT NULL DROP USER [COFIDIS2000\grpSQLArquitetosSDA];


IF DATABASE_PRINCIPAL_ID(''lnk_aw12012'') IS NOT NULL GRANT CONNECT TO [lnk_aw12012]   
IF DATABASE_PRINCIPAL_ID(''grafana_readonly'') IS NOT NULL GRANT CONNECT TO [grafana_readonly];
IF DATABASE_PRINCIPAL_ID(''COFIDIS2000\AGTSVC'') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\AGTSVC];
IF DATABASE_PRINCIPAL_ID(''COFIDIS2000\PIRS_SVC_UNN'') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\PIRS_SVC_UNN];
IF DATABASE_PRINCIPAL_ID(''COFIDIS2000\grpSQLArquitetosSDA'') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\grpSQLArquitetosSDA];



IF DATABASE_PRINCIPAL_ID(''grafana_readonly'') IS NULL CREATE USER [grafana_readonly] FOR LOGIN [grafana_readonly] WITH DEFAULT_SCHEMA =  [dbo];
IF DATABASE_PRINCIPAL_ID(''lnk_aw12012'') IS NULL CREATE USER [lnk_aw12012] FOR LOGIN [lnk_aw12012] WITH DEFAULT_SCHEMA =  [dbo];
IF DATABASE_PRINCIPAL_ID(''COFIDIS2000\PIRS_SVC_UNN'') IS NULL CREATE USER [COFIDIS2000\PIRS_SVC_UNN] WITHOUT LOGIN WITH DEFAULT_SCHEMA =  [dbo]; 
IF DATABASE_PRINCIPAL_ID(''COFIDIS2000\SPServices_SRV_PROD'') IS NULL CREATE USER [COFIDIS2000\SPServices_SRV_PROD] WITHOUT LOGIN WITH DEFAULT_SCHEMA =  [dbo]; 
IF DATABASE_PRINCIPAL_ID(''COFIDIS2000\AGTSVC'') IS NULL CREATE USER [COFIDIS2000\AGTSVC] WITHOUT LOGIN WITH DEFAULT_SCHEMA =  [dbo]; 
IF DATABASE_PRINCIPAL_ID(''COFIDIS2000\grpSQLArquitetosSDA'') IS NULL CREATE USER [COFIDIS2000\grpSQLArquitetosSDA] FOR LOGIN [COFIDIS2000\grpSQLArquitetosSDA] WITH DEFAULT_SCHEMA =  [dbo];

EXEC sp_addrolemember @rolename = ''db_datareader'', @membername = ''COFIDIS2000\AGTSVC'';
EXEC sp_addrolemember @rolename = ''db_datareader'', @membername = ''grafana_readonly'';
EXEC sp_addrolemember @rolename = ''db_datareader'', @membername = ''lnk_aw12012'';
EXEC sp_addrolemember @rolename = ''db_datareader'', @membername = ''COFIDIS2000\PIRS_SVC_UNN'';
EXEC sp_addrolemember @rolename = ''db_datareader'', @membername = ''COFIDIS2000\SPServices_SRV_PROD'';
EXEC sp_addrolemember @rolename = ''db_datareader'', @membername = ''COFIDIS2000\grpSQLArquitetosSDA'';


use cofcc_hds
go



IF DATABASE_PRINCIPAL_ID(''grafana_readonly'') IS NOT NULL DROP USER [grafana_readonly];
IF DATABASE_PRINCIPAL_ID(''lnk_aw12012'') IS NOT NULL DROP USER [lnk_aw12012];
IF DATABASE_PRINCIPAL_ID(''COFIDIS2000\PIRS_SVC_UNN'') IS NOT NULL DROP USER [COFIDIS2000\PIRS_SVC_UNN];
IF DATABASE_PRINCIPAL_ID(''COFIDIS2000\SPServices_SRV_PROD'') IS NOT NULL DROP USER [COFIDIS2000\SPServices_SRV_PROD];
IF DATABASE_PRINCIPAL_ID(''COFIDIS2000\AGTSVC'') IS NOT NULL DROP USER [COFIDIS2000\AGTSVC];
IF DATABASE_PRINCIPAL_ID(''COFIDIS2000\grpSQLArquitetosSDA'') IS NOT NULL DROP USER [COFIDIS2000\grpSQLArquitetosSDA];


IF DATABASE_PRINCIPAL_ID(''lnk_aw12012'') IS NOT NULL GRANT CONNECT TO [lnk_aw12012]   
IF DATABASE_PRINCIPAL_ID(''grafana_readonly'') IS NOT NULL GRANT CONNECT TO [grafana_readonly];
IF DATABASE_PRINCIPAL_ID(''COFIDIS2000\AGTSVC'') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\AGTSVC];
IF DATABASE_PRINCIPAL_ID(''COFIDIS2000\PIRS_SVC_UNN'') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\PIRS_SVC_UNN];
IF DATABASE_PRINCIPAL_ID(''COFIDIS2000\grpSQLArquitetosSDA'') IS NOT NULL GRANT CONNECT TO [COFIDIS2000\grpSQLArquitetosSDA];



IF DATABASE_PRINCIPAL_ID(''grafana_readonly'') IS NULL CREATE USER [grafana_readonly] FOR LOGIN [grafana_readonly] WITH DEFAULT_SCHEMA =  [dbo];
IF DATABASE_PRINCIPAL_ID(''lnk_aw12012'') IS NULL CREATE USER [lnk_aw12012] FOR LOGIN [lnk_aw12012] WITH DEFAULT_SCHEMA =  [dbo];
IF DATABASE_PRINCIPAL_ID(''COFIDIS2000\PIRS_SVC_UNN'') IS NULL CREATE USER [COFIDIS2000\PIRS_SVC_UNN] WITHOUT LOGIN WITH DEFAULT_SCHEMA =  [dbo]; 
IF DATABASE_PRINCIPAL_ID(''COFIDIS2000\SPServices_SRV_PROD'') IS NULL CREATE USER [COFIDIS2000\SPServices_SRV_PROD] WITHOUT LOGIN WITH DEFAULT_SCHEMA =  [dbo]; 
IF DATABASE_PRINCIPAL_ID(''COFIDIS2000\AGTSVC'') IS NULL CREATE USER [COFIDIS2000\AGTSVC] WITHOUT LOGIN WITH DEFAULT_SCHEMA =  [dbo]; 
IF DATABASE_PRINCIPAL_ID(''COFIDIS2000\grpSQLArquitetosSDA'') IS NULL CREATE USER [COFIDIS2000\grpSQLArquitetosSDA] FOR LOGIN [COFIDIS2000\grpSQLArquitetosSDA] WITH DEFAULT_SCHEMA =  [dbo];

EXEC sp_addrolemember @rolename = ''db_datareader'', @membername = ''COFIDIS2000\AGTSVC'';
EXEC sp_addrolemember @rolename = ''db_datareader'', @membername = ''grafana_readonly'';
EXEC sp_addrolemember @rolename = ''db_datareader'', @membername = ''lnk_aw12012'';
EXEC sp_addrolemember @rolename = ''db_datareader'', @membername = ''COFIDIS2000\PIRS_SVC_UNN'';
EXEC sp_addrolemember @rolename = ''db_datareader'', @membername = ''COFIDIS2000\SPServices_SRV_PROD'';
EXEC sp_addrolemember @rolename = ''db_datareader'', @membername = ''COFIDIS2000\grpSQLArquitetosSDA'';

') AT AW12012;